### ISSUE TITLE
CanvasOnChain: Create a SmartContract that stores the pixels

### ISSUE THREAD

**Issue by melanke** [scaffold-eth/scaffold-eth-2#1001]
Create a contract that stores the pixel coordinate, the author of the pixel placement and the color of the pixel.

We should only have a few color options.

Remember to validate the position of the pixel and if the color is valid.

When the contract is deployed it needs to already have a default drawing, something related to Batch11

**Comment by Abidoyesimze** [comment]
Will try working on this

**Comment by melanke** [comment]
omg, wrong repo

**Comment by Abidoyesimze** [comment]
oops
