### ISSUE TITLE
useScaffoldPerpareContractWrite & useScaffoldContractWrite

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#216]
### Description 
I propose we should have two options for developers : 
1. **`useScaffoldPerpareContractWrite`** : An utility writes hook which uses wagmi's `usePrepareContractWrite` and `useContractWrite` both internally and returns the value, returned from both hook. 
2. **`useScaffoldContractWrite`** : An utility write hook that uses `useContractWrite` without `usePrepareContractWrite`. 

### Reason 
Although wagmi suggests  `usePrepareContractWrite`  should be always used with `useContractWrite` but considering se-2 will be used by beginner, and also to do quick scaffolding....It would be great if we have `useScaffoldContractWrite` which don't use `usePrepareContractWrite` because if you use `usePrepareContractWrite` then you have to handle `error's` properly returned by the hook and also display them, if not we may get misleading error / not so usefull error also hard to figure out errors. 

checkout #215 

That said errors are also handled pretty well by `useScaffoldContractWrite` because we are wrapping `writeAsync` inside our `useTransactor` hook. Which shows good error without developer needing to handle and display them in the UI. 

I 100% understand the necessity of `usePrepareContractWrite`  and all the things it does internally, but it might be PITA for the person doing quick scaffolding and he needs to handle all the errors on the input level properly to give good UX. 

### Example : 
1. useScaffoldPreparedContractWrite.ts
```js 
export const useScaffoldPreparedContractWrite = (contractName: string, functionName: string, args?: any[], value?: string) => {
   ...
  const writeTx = useTransactor();

  const { config, ...restPrepareValues } = usePrepareContractWrite({
    chainId: configuredChain.id,
    address: deployedContractData?.address,
    abi: deployedContractData?.abi,
    args,
    functionName,
    overrides: {
      value: value ? utils.parseEther(value) : undefined,
    },
  });

  const wagmiContractWrite = useContractWrite(config);

  const sendContractWriteTx = async () => {
   ....
  };

  return {
    ...wagmiContractWrite,
    ...restPrepareValues, 
    writeAsync: sendContractWriteTx,
  };
};
```

2. useScaffoldContractWrite.ts 
```js
export const useScaffoldContractWrite = (contractName: string, functionName: string, args?: any[], value?: string) => {
   ...  
  const writeTx = useTransactor();

  const wagmiContractWrite = useContractWrite({
    mode: "recklesslyUnprepared",
    chainId: configuredChain.id,
    address: deployedContractData?.address,
    abi: deployedContractData?.abi,
    args,
    functionName,
    overrides: {
      value: value ? utils.parseEther(value) : undefined,
    },
  });

  const sendContractWriteTx = async () => {
  ...
  };

  return {
    ...wagmiContractWrite,
    // Overwrite wagmi's write async
    writeAsync: sendContractWriteTx,
  };
};

```

cc @carletex @rin-st @sverps

**Comment by carletex** [comment]
Austin encountered this issue yesterday while trying to send a tx with his iphone. When click "send" in the /debug page, it took him to the app store.

https://wagmi.sh/react/prepare-hooks#ios-app-link-constraints

![image](https://user-images.githubusercontent.com/2486142/222177698-d36b283e-89d1-4680-b033-f427571af958.png)

I guess the issue was number 2, which prepareHooks solve.

**Comment by technophile-04** [comment]
> Austin encountered this issue yesterday while trying to send a tx with his iphone. When click "send" in the /debug page, it took him to the app store.

I just deployed and tested with iphone and it solved now in v1 without using `prepareHook` 🙌

Here the app link :  https://test-goerli.vercel.app

Also, they have removed that section from here -> https://wagmi.sh/react/prepare-hooks#ios-app-link-constraints



Closing this 🙌
