### ISSUE TITLE
Migration from ethers to viem (and wagmi 1.*)

### ISSUE THREAD

**Issue by rin-st** [scaffold-eth/scaffold-eth-2#229]
What do you think about migrating to [Viem](https://viem.sh/), a new alternative to ethers.js and web3.js from the creators of wagmi?

[Why Viem](https://viem.sh/docs/introduction.html)

**Comment by carletex** [comment]
Thanks for bringing this Rinat! Just saw it the other day, and it's in my list to download and test it.

> It's unclear how mature Viem already is. In the wagmi project, I see they still use ethers (so even they haven't switched over yet to their own library). So it looks like a cool new lib, and their goal sounds really nice, but I'm unsure if it is stable enough to already switch over to it.

+1 

I've seen before how trying to use the shiny new libraries can ruin the stability of the project. As a rule, I'd never use a library that is so new, specially when the existing lib does the job well and the "only" benefit is "performance / bundle size "....where we don't really have a problem. The only thing that I don't like about ethers, is their DOCS haha

In any case, we should definitely use it outside of SE-2, get a feel of it, and when wagmi intregrates it (in their v1.0 I think) we can reconsider.

**Comment by rin-st** [comment]
> I've seen before how trying to use the shiny new libraries can ruin the stability of the project.

I'm too conservative to do that too most of the time, don't even remember when I did that. But for some reason, I decided to give Viem a try. Agree with you guys, let's test it outside of SE-2 and wait for integration to wagmi ([yes, it will be 1.0](https://github.com/wagmi-dev/viem/discussions/104#discussioncomment-5212300))

**Comment by carletex** [comment]
Closing this for now.... but let see how we feel about it in a few months or when wagmi v1.0 is out ;)

**Comment by jxom** [comment]
How do you feel about it now? 😀

**Comment by carletex** [comment]
@jxom Good enough to re-open the issue :)
