### ISSUE TITLE
TypeScript styleguide

### ISSUE THREAD

**Issue by sverps** [scaffold-eth/scaffold-eth-2#232]
I propose choosing and following a style guide to get more consistency throughout the code.

My choice would be to follow [google's style guide](https://google.github.io/styleguide/tsguide.html).

Some possible exceptions:

- To avoid having to rename practically all files, I think we could opt to disregard the filename rule.
- [anything else?]

**Comment by rin-st** [comment]
Agree with everything @carletex wrote.
>Interface vs Types

I prefer to use Types
---
Again, regarding [default export](https://google.github.io/styleguide/tsguide.html#exports)

Next.js supports lazy loading for named exports using `next/dynamic` [docs](https://nextjs.org/docs/advanced-features/dynamic-import#with-named-exports).

So, if you're ok to write one additional `then` for potential lazy loading, we probably don't need default exports anymore

**Comment by ByteAtATime** [comment]
My personal opinion, I think we can leave default exports as-is, since it's very common in React.
