### ISSUE TITLE
QR receiver code for connected wallet address

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#237]
It'll be handy to have a QR receiver code for the connected wallet in SE-2

Is this customizable in Rainbow kit? We could add it here as an button / direct qr embed (and also show more info about the connected wallet, as @technophile-04 suggested here https://github.com/scaffold-eth/se-2/issues/87#issuecomment-1375151789)

![image](https://user-images.githubusercontent.com/2486142/224693609-05e80a98-67a5-42c9-bc4c-8bd28004d4e0.png)

**Comment by rin-st** [comment]
> Is this customizable in Rainbow kit?

according to [docs](https://www.rainbowkit.com/docs/introduction) and github [1](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/AccountModal/AccountModal.tsx) [2](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/ProfileDetails/ProfileDetails.tsx) there is no way to do that :(
we can configure only disclaimer and app info here

---
<img width="730" alt="Снимок экрана 2023-03-15 в 22 23 04" src="https://user-images.githubusercontent.com/25638585/225406571-2a3207fd-2acf-4153-82a2-7754a305d183.png">

**Comment by carletex** [comment]
Let's hold on this for now. If we can't tweak the rainbow modal directly, we might think of another place to put it.

**Comment by KcPele** [comment]
ok

**Comment by technophile-04** [comment]
Closing this in favour of #446 🙌
