### ISSUE TITLE
Read hooks call contract function with incomplete args resulting in console errors

### ISSUE THREAD

**Issue by sverps** [scaffold-eth/scaffold-eth-2#249]
## Scenario

When using a contract read hook to call a function that requires some arguments, a common approach is to create a form to let a user provide his input. These form states are then used as params to pass into the args.

## Current behavior

Currently, the hook is triggered on each variable change, resulting in a lot of errors in the console as long as not all args are set and of the correct type. To resolve this, you need to either set the hook to `enabled: false` and create some custom condition when to enable it based on params or trigger it with the `refetch`.

## Proposed solution

I think a more intuitive behavior is to disable the hook when we know it would result in an error, and only call the contract function when the params are good. That way, the types force a dev to plug in correctly typed variables for args, and when a user using the UI does some action (i.e. fill in a form) that actually provides a value for the variables, only then is the actual contract function called.

## Benefits

- Reduce contract calls (or at least reduce triggers of the `wagmi` hook)
- Reduce a lot of boilerplate code to prevent these unnecessary calls
- Cleaner console output

**Comment by technophile-04** [comment]
Tysm @sverps  !! Even I noticed it while testing 

> I think a more intuitive behavior is to disable the hook when we know it would result in an error, and only call the contract function when the params are good.

Yup 💯, even `wagmi's` native hooks do the same thing, they don't make a request if args are undefined
