### ISSUE TITLE
External contract

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#271]
We have really nice hooks (on top of wagmi's) for interacting with contracts deployed from SE-2 (leveraging on the `hardhat_contracts.ts` file).

Let's find the best way to do something similar with external contracts. E.g. You want your dApp to interact with the DAI contract. SE1 use a `external_contracts.js` file.

Ideally, as a builder, I'd like to use it the same way we use our custom hooks (same autocomplete / types magic).

```ts
  const { writeAsync } = useScaffoldContractWrite({
    contractName: "DaiContract",
    functionName: "transfer",
    args: [address, amount],
  });
```

I guess we could do that right now if we make the builder paste (in the right format) the contract info in `hardhats_contracts.ts`. But that's not very friendly.

So maybe a `external_contracts.ts` with a more clear format? Using wagmi's cli?

Check out this comment from @technophile-04 https://github.com/scaffold-eth/se-2/pull/200#issuecomment-1485414504.

**Comment by KcPele** [comment]
the hook should accepts the ABI and address of the contract right?

**Comment by sverps** [comment]
I have made some progress on this (https://github.com/sverps/se-2/tree/feature/271-external-contracts) before my holidays. I'll see if I can find some time to pick this up again.
