### ISSUE TITLE
README docs: hooks (+ components)

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#273]
Let's have a section on the README that explains

**Hooks**

Explain that are built on top of wagmi's, autocomplete / types magic, etc.
- useScaffoldContractRead
- useScaffoldContractWrite
- useScaffoldEventSubscriber
- useDeployedContractInfo

Just a one-liner with an example.

E.g.

**useScaffoldContractRead**: Use this hook to read a value from your deployed contracts.

```ts

  const { data: totalCounter } = useScaffoldContractRead({
    contractName: "YourContract",
    functionName: "userGreetingCounter",
    args: ["THE_ADDDRESS_AS_AN_ARGUMENT"],
  });
```

**Components**

Explain the main one with a screenshot of each one:

![image](https://user-images.githubusercontent.com/2486142/228882137-fcdd81a0-a5f1-4c59-ab92-4c3e61252ddf.png)

E.g.

**Address**: It displays the given address, with ENS resolution (name + avatar), copy icon and link to the blockexplorer
![image](https://user-images.githubusercontent.com/2486142/228882504-fed2301c-8464-40fd-9753-dc8ed4995b7f.png)

----

Maybe here:

![image](https://user-images.githubusercontent.com/2486142/228882636-bbb121a2-0643-4358-b42a-03acdac0f760.png)

We could add:
- A handful of components, hooks, and utils. See [link to section](#)

----

Anyway, my copys suck, this are just examples :D

**Comment by carletex** [comment]
Related to #91

**Comment by KcPele** [comment]
> Let's have a section on the README that explains
> 
> **Hooks**
> 
> Explain that are built on top of wagmi's, autocomplete / types magic, etc.
> 
> * useScaffoldContractRead
> * useScaffoldContractWrite
> * useScaffoldEventSubscriber
> * useDeployedContractInfo
> 
> Just a one-liner with an example.
> 
> E.g.
> 
> **useScaffoldContractRead**: Use this hook to read a value from your deployed contracts.
> 
> ```ts
>   const { data: totalCounter } = useScaffoldContractRead({
>     contractName: "YourContract",
>     functionName: "userGreetingCounter",
>     args: ["THE_ADDDRESS_AS_AN_ARGUMENT"],
>   });
> ```
> 
> **Components**
> 
> Explain the main one with a screenshot of each one:
> 
> ![image](https://user-images.githubusercontent.com/2486142/228882137-fcdd81a0-a5f1-4c59-ab92-4c3e61252ddf.png)
> 
> E.g.
> 
> **Address**: It displays the given address, with ENS resolution (name + avatar), copy icon and link to the blockexplorer ![image](https://user-images.githubusercontent.com/2486142/228882504-fed2301c-8464-40fd-9753-dc8ed4995b7f.png)
> 
> Maybe here:
> 
> ![image](https://user-images.githubusercontent.com/2486142/228882636-bbb121a2-0643-4358-b42a-03acdac0f760.png)
> 
> We could add:
> 
> * A handful of components, hooks, and utils. See [link to section](#)
> 
> Anyway, my copys suck, this are just examples :D

Should the examples be from the codebase(example UI) or any good example that works and is simple

**Comment by KcPele** [comment]
checkout these pr #302

**Comment by carletex** [comment]
The first version of this was merged on https://github.com/scaffold-eth/se-2/pull/302 but I think we need to improve it a bit.


1. A better section name than "Hook Example"
2. An intro to the section: 
    -  Explain the goal of these hooks: interact with contracts deployed FROM SE-2). 
    - Maybe say that they are a wrapper on top of wagmi, and you can use wagmi directly for specific cases / external contracts?
4. Link the section on the TOC
![image](https://user-images.githubusercontent.com/2486142/232431251-43aeab89-c2ee-4b37-996e-9a284ce6c10f.png)
5. Better hook description: I feel that the current description can be 100% inferred by the hook name, so we might want to have a description that clarifies something. "Use this hook to get the matching contract info from the contracts file generated by yarn deploy" This is confusing to me.
6. "Use to gets a deployed contract by contract name and returns a contract instance Can also be use to read and write to the deployed smart contract" I think there are some spelling mistakes ("use to gets", "also be use") here and missing some punctuation?

cc @edakturk14

**Comment by KcPele** [comment]
ok, working on that Ser

**Comment by edakturk14** [comment]
hey @carletex & @KcPele,

Made a few tweaks to the README.

- Updated the introduction section
- Added descriptions to hooks and changed some grammar

Please lmk if you have any q or comments & i can make the changes needed. ty!
