### ISSUE TITLE
Having multiple instances of `RainbowKitCustomConnectButton` on a page breaks functionality

### ISSUE THREAD

**Issue by sigmachirality** [scaffold-eth/scaffold-eth-2#295]
**Steps to reproduce:**

1. Add a `RainbowKitCustomConnectButton` to the `/index` page. Alternatively, add two `RainbowKitCustomConnectButton` buttons from `~~/components/scaffold-eth` anywhere in the app.
2. Attempt to disconnect from the app.

Note: this issue does not occur when an instance of the `RainbowKitCustomConnectButton` is on the active page with an instance of the base `ConnectButton` from `@rainbow-me/rainbowkit`.

This might be a quirk of my local development environment - I can put some more cycles into investigating this later this week, especially if nobody else can reproduce this.

This could also be a bug with the RainbowKit headless components or wagmi.

**Comment by sigmachirality** [comment]
Suspect it might have to do with the functionality in SE-2 toggled by `walletAutoConnect: true` in the `scaffold.config.ts` file.

**Comment by technophile-04** [comment]
Hey @sigmachirality  for raising the issue, could elaborate more on how to reproduce it also what error you get ? , I tried creating multiple instances of `RainbowKitCustomConnectButton` on a page and it works fine but maybe I am missing something 

https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/392a8c66-a428-4e36-9cfe-e56be97bebbc
