### ISSUE TITLE
Mainnet hardcoded to be a network option => Create a better switch network workflow

### ISSUE THREAD

**Issue by kevinjoshi46b** [scaffold-eth/scaffold-eth-2#300]
I am curious why is mainnet hardcoded to be a compulsory network option when the user is on a wrong network?

https://github.com/scaffold-eth/se-2/blob/ce83d166df62083a3aac86a6dda1802737a02fa8/packages/nextjs/services/web3/wagmiConnectors.tsx#L23

![image](https://user-images.githubusercontent.com/62877695/230841879-2cfbbf83-f3c6-4e7d-a52e-b5e590e0e56e.png)

**Comment by carletex** [comment]
We want mainnet ENS resolution for ENS, on any target network.

We should hide it on that modal, tho.

**Comment by kevinjoshi46b** [comment]
> We want mainnet ENS resolution, on any target network.

This was literally the comment above, that I didn't read 🤦

> We should hide it on that modal, tho.

I will look into fixing this

**Comment by carletex** [comment]
haha, no worries. Thank you!

> I will look into fixing this

It might be tricky to tweak those modals. Check https://github.com/scaffold-eth/se-2/issues/237

One solution could be not using a modal, and just a dropdown: When you click "wrong network" you get a menu dropdown and there is the "targetNetwork" and the disconnect button. (in `RainbowKitCustomConnectButton.tsx`)

What do you think?

**Comment by kevinjoshi46b** [comment]
Just a thought, since the app will always only be on one active network at a time, why even create a dropdown? The dropdown will always just have one network option right. So why not just make the "Wrong network" button an action button which on click will trigger the network switch 🤔

**Comment by carletex** [comment]
> So why not just make the "Wrong network" button an action button which on click will trigger the network switch

Because you can't disconnect. Using wallet connect, sometimes the switch doesn't trigger and if you don't have the disconnect button you'd get locked.

**Comment by kevinjoshi46b** [comment]
> Because you can't disconnect. Using wallet connect, sometimes the switch doesn't trigger and if you don't have the disconnect button you'd get locked.

Ooohh I was not aware of this. Cool then ig dropdown sounds good. I can look into working on this. You can assign me this issue 🙌

**Comment by tokodev** [comment]
> I'd go with the button dropdown route, at least for the switch network. Depending on how we like it we can rethink #237

I like the idea, I'll work on it using https://daisyui.com/components/dropdown/ and the features of wagmi / rainbowkit. Can you assign me @carletex?

**Comment by carletex** [comment]
> I like the idea, I'll work on it using https://daisyui.com/components/dropdown/ and the features of wagmi / rainbowkit. Can you assign me @carletex?

Great, thanks! Assigned.

For the disconnect / switch actions you can use wagmi's `useDisconnect`and `useSwitchNetwork`. Check how rainbow kit does it [here]( https://github.com/rainbow-me/rainbowkit/blob/737a1d6ee13f409fc2060fa55d6c741a7fa574db/packages/rainbowkit/src/components/ChainModal/ChainModal.tsx)

**Comment by kevinjoshi46b** [comment]
> About dropdown, why don't we just create a modal just like the rainbowkit's one. Ya probably not 100% ditto but similar. I am suggesting this because I feel it will be more in sync with the design.

@carletex what are your opinions on this though?
