### ISSUE TITLE
Foundry package

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#318]
We are working on a CLI tool (#251) that will allow SE-2 users to choose between hardhat / foundry when setting up their project.

The CLI is not ready yet, but we want to start building the foundry package (`packages/foundry`), setting the libs/config that you need to do the same things that we do with the hardhat package: 

- Deploy a smart contract
- Run a localhost node/rpc where you can deploy contracts and where we can point from our front end. 
- Have a sample contract (same) + a test
- Allow configuring networks to deploy to (foundry config file?)
- Generate the "deployedContracts.ts" file in the nextjs folder.
- Generate a burner/deployer account

Ideally, we want to have the same  root "CLI commands API" that we use for hardhat:

- `yarn chain`: start the local node / rpc
- `yarn deploy --network sepolia`: deploys your contract to the target network.
- `yarn generate`: generate a random account
- `yarn account`: show the QR for the generated account and the balances in all the configured networks

(maybe last two could be shared and don't need a new implementation for Foundry.)

**Comment by supernovahs** [comment]
I would like to contribute

**Comment by luloxi** [comment]
I want to collaborate in this change! 

PS: I don't see any good reason to do another implementation of "yarn generate" and "yarn account". Mnemonics are mnemonics

**Comment by technophile-04** [comment]
For the deployments part I think we should keep an eye on [forge-deploy](https://github.com/wighawag/forge-deploy) it is created by the same developer who made [hardhat-deploy](https://github.com/wighawag/hardhat-deploy)(which is currently being used for deployments / managing deployments with abi in our Hardhat-based SE-2 also our [custom hooks](https://github.com/scaffold-eth/scaffold-eth-2#interacting-with-your-smart-contracts-se-2-custom-hooks) relies on the structure which it creates after deployments ). [forge-deploy](https://github.com/wighawag/forge-deploy) is trying to keep things similar to hardhat-deploy so might help us. 

Nevertheless, don't want to get ahead of ourselves also [forge-deploy](https://github.com/wighawag/forge-deploy) is **under active development** so might be a bit unstable. Just wanted to mention about it here 🙌

**Comment by luloxi** [comment]
Just found this repo, might be useful for connecting Foundry with the other parts of SE2

[forge-exec](https://github.com/wighawag/forge-exec)

Btw, is there a branch of SE2 with foundry that I can try out, so I can see how the current implmentation is working?

**Comment by jrcarlos2000** [comment]
Q : is it required for the /foundry package to be able to work without the /hardhat package ? Since as mentioned in the issue, some commands can be shared.

**Comment by carletex** [comment]
Hey @jrcarlos2000 

> Q : is it required for the /foundry package to be able to work without the /hardhat package ? Since as mentioned in the issue, some commands can be shared so maybe having them together would be a good option

Nop. As mentioned on the issue, the CLI will let you choose between them. In most setups, people use either Hardhat or Foundry (I've seen some repos where people use both, but not the regular setup).

The main idea of the CLI is getting a non-bloated repo.

But if you are working on a PR, you can just create a `packages/foundry` alongside `packages/hardhat`. We will do the logic to select one of the two in the CLI.

> Ideally, we want to have the same root "CLI commands API" that we use for hardhat

I was mentioning this because people are used to the scaffold-eth commands (yarn chain, deploy, etc), so it'd be nice if the foundry packages also use the same.

lmk if you have any questions! Thanks Carlos!

**Comment by jrcarlos2000** [comment]
got it, was asking this because i have used ```npx hardhat node``` alongisde foundry most of the time. Seems like now there has to be an independent similar functionality inside the  foundry package

**Comment by kamikazebr** [comment]
> But if you are working on a PR, you can just create a `packages/foundry` alongside `packages/hardhat`. We will do the logic to select one of the two in the CLI.

That its cool idea. I most time use both them together. I think more and more people migrating to foundry will make we go solo foundry instead mixed.

**Comment by technophile-04** [comment]
Thanks to @jrcarlos2000 we have basics of foundry setup on [`foundry`](https://github.com/scaffold-eth/scaffold-eth-2/tree/foundry#readme) branch 🙌....Please feel free to tinker around with it and add any issues / tackle issue on #394 

Thanks all 🙌
