### ISSUE TITLE
the debug contract selected should stay through a reload 

### ISSUE THREAD

**Issue by austintgriffith** [scaffold-eth/scaffold-eth-2#325]
if I have a contract selected on the debug tab and I reload it should stay selected

![image](https://user-images.githubusercontent.com/2653167/234420351-92452935-77dc-4f1f-92e2-e856b4db8105.png)

right now it switches back to first contract

**Comment by kevinjoshi46b** [comment]
Probably can be done using local storage / cookies.

**Comment by Bogarne** [comment]
Completed local storage support for selected contract. 
https://github.com/scaffold-eth/scaffold-eth-2/pull/326

**Comment by KcPele** [comment]
I have made a pr to this issue #331

**Comment by Bogarne** [comment]
@KcPele, thank you for your work. However, my pull request was created earlier and this is mentioned.

**Comment by Bogarne** [comment]
@KcPele, thank you for your work. However, my pull request was created earlier and this is mentioned.

**Comment by KcPele** [comment]
So sorry. I will remove it

**Comment by Bogarne** [comment]
@KcPele I wanted to bring something to your attention regarding working with local storage. It is recommended to include try-catch blocks to handle cases when data is null or empty and to assign it to a separate variable. This is an example of a storage object with the get() and set() methods:
```
const storage = {
  get() {
    try {
      const data = window.localStorage.getItem("myData");

      if (data === null || data === "") {
        return [];
      }

      return JSON.parse(data);
    } catch (error) {
      console.log(`Get data from LocalStorage isn't allowed. ${error}`);
      return [];
    }
  },
  set(data) {
    try {
      window.localStorage.setItem("myData", JSON.stringify(data));
    } catch (error) {
      console.log(`Set data to LocalStorage isn't allowed. ${error}`);
    }
  },
};
```

**Comment by KcPele** [comment]
I had already made provision for that. That was why I did not include
trycatch

**Comment by KcPele** [comment]
am removing this pr. i just saw the one you did
