### ISSUE TITLE
Do you support EIP-2535 Diamonds?

### ISSUE THREAD

**Issue by Osub** [scaffold-eth/scaffold-eth-2#328]
Do you support EIP-2535 Diamonds?

**Comment by Bogarne** [comment]
Hi @Osub. Yes, the application supports the EIP-2535 Diamonds standard. It's not just about supporting EIP-2535, but rather understanding how to properly implement the standard in your smart contract project to take advantage of its benefits. If you use the EIP-2535 Diamond standard to create a contract, you can add new features to it without the need to redeploy the entire contract.

1. When you deploy a Diamond contract, you define a set of facets that contain the original set of functions and state variables.
2. If you want to add new functions to your contract, you can create a new facet that contains the new functions and state variables.
3. Then, you can use the `diamondCut` function of the Diamond contract to add the new aspect of the contract.
4. After adding the new facet, your ReactJS application can call the new functions in the facet just like it would call any other function in the contract. 

Discussions on similar topics can be held, for example, in a [Telegram group](https://t.me/+PXu_P6pps5I5ZmUx).
