### ISSUE TITLE
bug: hydration fails due to mismatch caused by usehooks-ts bug

### ISSUE THREAD

**Issue by sverps** [scaffold-eth/scaffold-eth-2#340]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

When using `useLocalStorage`, in certain cases, Next throws a "hydration failed" error due to server/client mismatch.

### Expected Behavior

No hydration failures

### Anything else?

This is caused by a bug in `useLocalStorage` which is addressed in an [open PR](https://github.com/juliencrn/usehooks-ts/pull/251) on their end.

It appears, however, that `usehooks-ts` is no longer maintained. Should we look into alternatives? Options are:

- Create workarounds where needed (with risk that users aren't aware of these issues and run into them themselves)
- Ditch the dependency in favor of a newer hooks lib
- Ditch the dependency in favor of our own set of utility hooks

**Comment by sverps** [comment]
@damianmarti @carletex @technophile-04 I think the best approach would be to just maintain these couple of utility hooks that we use ourselves. They're generally not very complex, and then we can drop an unmaintained dependency (I didn't find any decently maintained alternatives).

I'm up for creating a PR for this, what do you guys think?

**Comment by technophile-04** [comment]
I was actually liking `ushooks-ts` because it was great utility to go along with nextjs but seeing it is no longer maintained is kinda off :( 

The closest option I could find was [beautiful-react-hooks](https://github.com/antonioru/beautiful-react-hooks) but it's not that minimal and to the point 

---

> best approach would be to just maintain these couple of utility hooks that we use ourselves. They're generally not very complex, and then we can drop an unmaintained dependency

Yup I am leaning more towards this option

**Comment by carletex** [comment]
We use 5 hooks from that lib:

![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/2486142/446e34aa-ea30-4106-a492-e71e9058d34f)

Since we only have an issue with the localStorage one... another option will be to create a patch for it.

https://yarnpkg.com/cli/patch

**Comment by damianmarti** [comment]
Yes, I think we can patch it for now.

The fix is a one-line change https://github.com/juliencrn/usehooks-ts/pull/251/files#diff-a62dfbc133bd75ac4118dba29eb74fcb4cd6f767cd5a07e8ebe919dc92540f33R39

**Comment by damianmarti** [comment]
I created a PR to fix it with a patch to usehooks-ts useLocalStorage hook (if we decide this is the best approach).

I tested it by applying the patch at https://github.com/scaffold-eth/scaffold-eth-2/pull/326 and it worked ok!

**Comment by technophile-04** [comment]
> another option will be to create a patch for it.    https://yarnpkg.com/cli/patch

Ohhhh didn't knew about it 


> Yes, I think we can patch it for now. The fix is a one-line change

+++

**Comment by sverps** [comment]
Sounds good to me :+1: 

Meanwhile I have received response from the maintainer on Telegram, and he said he was going to look into merging a couple of long-standing open issues, so hopefully this will get fixed soon-ish... :crossed_fingers:
