### ISSUE TITLE
bug: type error in useScaffoldContract/EvenHistory when deployed multiple contracts

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#344]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

When you deploy two or more contracts and run `yarn next:check-types` you get `types error` for `useScaffoldContract/EventHistory` : 

 
![Screenshot 2023-05-13 at 9 36 57 AM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/7943159e-c7e8-4d85-9b0b-ba8f764d1944)

### Expected Behavior

No type error should be thrown even when using multiple contracts

### Steps To Reproduce

1. Checkout to [`bug/useContract-eventHistory`](https://github.com/scaffold-eth/scaffold-eth-2/tree/bug/useContract-eventHistory) branch
2. `yarn chain`
3. `yarn deploy`
4. `yarn next:check-types`

### Anything else?

The problem is occurring due to type `abi` of wagmi's `useContract` hook mismatch.

According to me (I may be completely wrong, just a wild guess) : 
```ts
// wagmi is expecting only union of abiType | undefined 
abi : readonly [{...}] | undefined 

// but we are passing abiType | abiType | undefined
readonly[{...}] | readonly[{...}] | undefined
```

cc @sverps for the fix  🙌

**Comment by sverps** [comment]
I think a simple type assertion should suffice. Since we define our param and return types ourselves, we don't rely on any type inference inside the hook. Opened a PR for it.
