### ISSUE TITLE
bug: Cannot invoke functions with array parameters

### ISSUE THREAD

**Issue by moltam89** [scaffold-eth/scaffold-eth-2#361]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

Deploy a contract with a function which contains an address array parameter:
_function addAddresssArray(address[] calldata addressesArray) {}..._
 
 On the "Debug Contracts" page there will be a Write function which accepts  _address[] addressesArray_.
 
 Invoking the function fails with an error:
_[0x55E07199E937d42aBe9294904Ec8E279d5a44766,0xFD3b5643Fe2c63EE2FbD38143ed551A6cd4d5cB8]_ 
 **invalid value for array (argument="value", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)**
 

### Expected Behavior

We can invoke the function without the error.

### Steps To Reproduce

You can cherry-pick this [commit](https://github.com/moltam89/scaffold-eth-2/commit/29d4d2bb4a307ed1acbea999b1bf5230202edfc0) to use a simple contract with which the error can be reproduced.

Other types are affected as well, e.g. we cannot use uint[]/bool[] arrays with [0x01,0x01].

<img width="940" alt="image" src="https://github.com/scaffold-eth/scaffold-eth-2/assets/1397179/fbbff91c-98b3-4525-bae4-c93235be7378">

### Anything else?

I think the error is in [getParsedContractFunctionArgs](https://github.com/scaffold-eth/scaffold-eth-2/blob/62b51cb04377e6405f5d6019fd0b3f7b6751e9d2/packages/nextjs/components/scaffold-eth/Contract/utilsContract.tsx#L178) where JSON.parse is used on the array, but JSON.parse cannot handle hexadecimal values.

**Comment by sverps** [comment]
The array fields internally do a `JSON.parse(valueOfArg)`, so you should enter valid JSON. Try with `["c54C244200d657650087455869f1aD168537d3B3"]`, that should work, I believe.

**Comment by moltam89** [comment]
Thanks @sverps ,

I missed this one.

Best,
Tamas
