### ISSUE TITLE
README: Add a section about `scaffold.config.ts`

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#382]
### Description : 
[`scaffold.config.ts`](https://github.com/scaffold-eth/scaffold-eth-2/blob/main/packages/nextjs/scaffold.config.ts) seems one of the imp files in SE-2 and is also used as single source of truth for the `network` on which DApp lives. People might overlook the mentions of `scaffold.config` in the current README, So let's have a section about `scaffold.config` describing each configurable property / API key in a short description . 

Also checkout https://github.com/scaffold-eth/scaffold-eth-2/pull/381#discussion_r1234186642

**Comment by KcPele** [comment]
Are you working on it or I can go ahead and continue

**Comment by KcPele** [comment]
#384

**Comment by Pabl0cks** [comment]
Closing the issue, got merged yesterday 🙌
