### ISSUE TITLE
bug: tailwind dark theme can make things hard to tell apart

### ISSUE THREAD

**Issue by portdeveloper** [scaffold-eth/scaffold-eth-2#397]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

Currently, if a page is in light mode,
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/108868128/4bc74bff-8cb8-4274-8b0d-ee18c139e5c8)
Everything can be easily seen, but since SE-2 uses the same color for secondary and base-200, it is impossible to tell the difference in dark mode. Here is how the same page looks in dark mode:
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/108868128/ee63d660-a533-41bb-8aa7-cc2239874d91)

Here is the current code for dark theme configuration:
`scaffoldEthDark: {
          primary: "#212638",
          "primary-content": "#F9FBFF",
          secondary: "#2A3655", 
          "secondary-content": "#F9FBFF",
          accent: "#4969A6",
          "accent-content": "#F9FBFF",
          neutral: "#F9FBFF",
          "neutral-content": "#385183",
          "base-100": "#385183",
          "base-200": "#2A3655",
          "base-300": "#212638",
          "base-content": "#F9FBFF",
          info: "#385183",
          success: "#34EEB6",
          warning: "#FFCF72",
          error: "#FF8863",

          "--rounded-btn": "9999rem",

          ".tooltip": {
            "--tooltip-tail": "6px",
            "--tooltip-color": "hsl(var(--p))",
          },
        },`

My suggestion is to change `secondary: "#2A3655",` to "secondary: "#323f61", achieving this:
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/108868128/f2116f5d-52cc-4890-9b14-21a688d23d78)

This will help with default colors in dark mode. I think if something is easily told apart in light mode, the same should apply to dark mode as well.

Let me know what you think about this situation.

**Comment by carletex** [comment]
Yep, this makes a lot of sense @portdeveloper 

base-200 is being used as the page background by default, so bg-secondary (btn-secondary, etc) won't display correctly on dark mode.

**Comment by sverps** [comment]
Nice one :+1:
