### ISSUE TITLE
bug: Prettier defaults to 2 tabWidth in .sol files

### ISSUE THREAD

**Issue by portdeveloper** [scaffold-eth/scaffold-eth-2#401]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

Currently, the .prettierrc.json file in packages/hardhat contains the following:
`{
    "arrowParens": "avoid",
    "printWidth": 120,
    "tabWidth": 2,
    "trailingComma": "all"
  }`

This results in formatting the .sol files in a wrong way.
Before formatting:
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/108868128/e59c3fb0-1a55-4cdf-8fd8-16e53297a61f)
After formatting:
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/108868128/f0afb083-5dfc-4ab8-a0f5-54bcaf4a0ef7)

### Expected Behavior

The solidity files should be formatted according to their own set of rules.
I suggest using a different set of rules for solidity:
`{
  "arrowParens": "avoid",
  "printWidth": 120,
  "tabWidth": 2,
  "trailingComma": "all",
  "overrides": [
    {
      "files": "*.sol",
      "options": {
        "printWidth": 80,
        "tabWidth": 4,
        "useTabs": true,
        "singleQuote": false,
        "bracketSpacing": true,
        "explicitTypes": "always"
      }
    }
  ]
}
`
as per 
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/108868128/52dd9f7e-6c53-4d19-a19a-0ac974d50946)

This changes the original style a little bit but ensures standardization between different projects using scaffold-eth 2.

### Steps To Reproduce

I am using a fresh install of vscode, nothing is different from normal except the font size is higher. Here are the extensions I use:
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/108868128/81450179-83ae-4992-b6e6-8c3a6fee3266)

### Anything else?

I am open to any kind of feedback/criticism!

**Comment by sverps** [comment]
Sounds like a good idea? :+1:
