### ISSUE TITLE
bug: Vercel deployment fails

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#419]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

Running : `yarn vercel` 

![Screenshot 2023-07-14 at 12 16 18 AM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/36c05f2d-5920-4b54-a6f5-2b519b1e43a2)

### Steps To Reproduce

**Alternatively to reproduce locally** : 
Update viem and wagmi to latest version : 
1.`yarn workspace @se-2/nextjs up wagmi viem`

Run check-types : 
2.`yarn next:check-types`

However through above steps you get different type errors then `vercel` : 
![Screenshot 2023-07-14 at 1 11 15 AM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/c1ef1a49-ae53-47f1-bafc-ff83ad6f2784)

### Anything else?

**I think** the reason its failing on vercel deployement and not locally is because since we have `^` for `viem` and `wagmi` in `package.json` because of which on Vercel while `yarn install` it gets latest `patch` version of both `viem` and `wagmi` and it seems that in latest `viem` and `wagmi` its broken. 

I think this problem is again related to -> https://github.com/wagmi-dev/wagmi/pull/2421#issue-1724776783

**Comment by carletex** [comment]
Thanks for reporting this Shiv.

What I don't understand is why Vercel installs a different version of the packages. Even if we have `^` in `package.json`, it should take the exact version from `yarn.lock` (that's the goal of this file!)

**Comment by technophile-04** [comment]
> What I don't understand is why Vercel installs a different version of the packages. Even if we have ^ in package.json, it should take the exact version from yarn.lock (that's the goal of this file!)

Yeah this makes sense !! 

I tried going through the deployment logs and found this : 
![Screenshot 2023-07-14 at 2 35 47 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/0bdc33b1-72d8-4ad3-8fd8-1a1a91af6baf)

Also if you look at the souce uploaded it dosen't have `yarn.lock` (I think because we are just uploading nextjs workspace and `yarn.lock` is present at root ?)

![Screenshot 2023-07-14 at 2 39 55 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/bcf21925-6da5-4ed7-8bec-16a643e9f88b)

**Comment by carletex** [comment]
Oh damn, you are right @technophile-04!! Thanks for looking into it. 

Maybe we could explore if there is a way to make a dedicated `yarn.lock` for each package?? (this will also be great for the CLI)

I think we can merge PRs #420 #421 for now

**Comment by carletex** [comment]
Another option is to make the root `yarn.lock` avaliable on the Vercel build (I think we look for something similar when playing when moving the `scaffold.config.ts` to the root of the repo)

**Comment by technophile-04** [comment]
> Maybe we could explore if there is a way to make a dedicated yarn.lock for each package?? (this will also be great for the CLI)

Yes yes will research on this nicely 

> Another option is to make the root yarn.lock available on the Vercel build (I think we look for something similar when playing with moving the scaffold.config.ts to the root of the repo)

Yup but with this option we had to mention `root directory` manually while deployemnt :( checkout point 1. of -> https://github.com/scaffold-eth/scaffold-eth-2/pull/231#issuecomment-1472265152

I have also created some discussion on vercel  regarding this : 
https://github.com/vercel/vercel/discussions/10211
https://github.com/orgs/vercel/discussions/2145

Nevertheless, I like the first option more having a dedicated `yarn.lock` if that's feasible but let's see 🙌

**Comment by technophile-04** [comment]
> Maybe we could explore if there is a way to make a dedicated yarn.lock for each package?? (this will also be great for the CLI)

I found this -> https://github.com/yarnpkg/berry/issues/1223...I think there is no direct solution to doing this in `yarn` :( .... There are some hacky solutions mentioned in the issue using some people's plugin but I went through and didn't find any stable, well maintained and regularly used plugin 

cc @rin-st @sverps also if they have some better approach or if I am missing and there might an easy solution already (because I feel this should have been present in `yarn` already). 

Also just mentioning `pnpm` here 😅 (It's workspaces has this option to create separate `lock` files)  ....I tried it out and its really good also we might also benefit from it using it in our CLI

**Comment by carletex** [comment]
> Also just mentioning pnpm here sweat_smile (It's workspaces has this option to create separate lock files) ....I tried it out and its really good also we might also benefit from it using it in our CLI due to its some what faster installations

We kept using `yarn` for historical reasons and it was easy to set up. But I won't be opposed to switching to pnpm if we have a good reason for it (like the per-package lock files) It supports monorepos too and it seems to be super fast.

But `yarn chain` etc is a classic in SE, so it looks like a big deal to me haha. I just texted Austin to get his take.

But also let's make sure that there isn't an easier solution that doesn't imply switching.

**Comment by rin-st** [comment]
I believe `pnpm` is a good solution.

**Comment by carletex** [comment]
@technophile-04 could you draft a PR (against main) for the `pnpm` "tests" that you made when you have the chance? So we can also see how pnpm looks on SE-2.

I really like the individual lock files, and it seems that's a modern and performant solution.

**Comment by technophile-04** [comment]
> @technophile-04 could you draft a PR (against main) for the pnpm "tests" that you made when you have the chance? So we can also see how pnpm looks on SE-2.

For sure !!!! lol I deleted all the changes but the migration is pretty much straightforward forward and easy so will draft a PR soon 🙌
