### ISSUE TITLE
bug: Vercel deployment via UI (connected to Github repo) fails, despite `yarn vercel` working from local CLI

### ISSUE THREAD

**Issue by webthethird** [scaffold-eth/scaffold-eth-2#428]
### Is there an existing issue for this?

- [x] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

I've connected my repository, created from SE-2, to Vercel via their UI, as recommended in the readme. But for every PR I make, Vercel fails to deploy to the preview environment due to an `ERESOLVE unable to resolve dependency tree` error, despite the fact that `yarn vercel` works just fine for me locally.

Note: on my end, I have Vercel CLI 28.20.0, but in the UI I can see that it's using Vercel CLI 31.0.3. The newer version seems to think there is a dependency conflict (see the screenshot below).

### Expected Behavior

Deploying to Vercel from my machine using the older CLI version works without issues, so I expected the PR deployments to work as well.

### Steps To Reproduce

Fork my repo: https://github.com/webthethird/habitat.git
Log into the Vercel UI, create a new project, and connect it to the forked repo.
Watch it fail.

### Anything else?

![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/6509209/088a2c8f-80f7-4d45-9f37-bc6d0a82fec0)

**Comment by technophile-04** [comment]
Hey @webthethird, I think in https://github.com/webthethird/habitat.git you have both `package-lock.json` and `yarn.lock` and in the SS is see `vercel UI` is trying to `npm install` instead of `yarn install` 

I think you should probably remove `package-lock.json` and then try

**Comment by webthethird** [comment]
*face palm*
That did the trick, thank you

**Comment by anton-karlovskiy** [comment]
Hello @technophile-04

Could you please have a look at https://github.com/scaffold-eth/se-2-challenges/issues/193?

Thanks.
