### ISSUE TITLE
bug: using `useAccount` address causes hydration error

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#453]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

It seems that displaying simple `address` from `useAccount` give "Hydration Error" : 

![Screenshot 2023-07-26 at 8 52 18 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/7217cd52-c219-46e8-96ce-5a437586dc22)

### Steps To Reproduce

![Screenshot 2023-07-26 at 8 55 29 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/d291cc8e-4a9e-461b-8672-f47b94487c7e)

### Anything else?

I was just trying to reproduce this normal wagmi-rainbowkit starter kit using [`create-wagmi`](https://wagmi.sh/cli/create-wagmi#templates)

But it seems that they are using very latest version of next and they have wrapped whole logic in the component which is marked as "use client" checkout ->  https://github.com/technophile-04/wagmi-debug/blob/750944c40657d94bf503878108b660d87a7e32d7/src/components/Connected.tsx#L1

I will try to debug it more in SE-2 itself but CCing @carletex @rin-st @sverps if something clicks up

**Comment by rin-st** [comment]
https://github.com/scaffold-eth/scaffold-eth-2/commit/cc1af9f5b227085767b05006baca88b2ca7a74d5 - wagmi config `autoConnect` was `false`. We used custom `useAutoConnect` and it connected after the first renders. Log address - it's `undefined` on the first renders, so there is no hydration error.

After https://github.com/scaffold-eth/scaffold-eth-2/pull/412 it changed, wagmi config `autoConnect` is true, so `useAccount` has data on the first render. It's good for react apps but not so good for next because that hydration error appears.

To fix it we can write a simple wrapper using `useMounted`, so there will be no error.

**Comment by technophile-04** [comment]
### Description : 

So I have been tinkering in the branch [play/useAutoConnect-useAccount](https://github.com/scaffold-eth/scaffold-eth-2/tree/play/useAutoConnect-useAccount) and setup few things there to test : 

1. Put `useAutoConnect` back from #412 
2. Setup  our own `useLocalStorage` which is just copy-past from `useHooks-ts` (without patch i.e #340) to tinker around 
3. Have 2 contracts for deployment to test https://github.com/scaffold-eth/scaffold-eth-2/pull/326#discussion_r1204592364


Now  if try auto connect functionality it works since we do not have patch in place i.e we are using `readValue` in useState of `useLocalStorage` instead of patch i.e -> https://github.com/juliencrn/usehooks-ts/pull/251/files

When use `useLocalStorage` with `readValue` the auto connect functionality works nicely but this problem arises -> https://github.com/scaffold-eth/scaffold-eth-2/pull/326#discussion_r1204592364 : 

| YourContarct is selected but not highlight | hydration warning in console | 
| ------------------------------------------| -----------------------------| 
|![Screenshot 2023-07-28 at 6 58 53 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/58fa5f86-bf3a-40eb-8cb5-fb6ae047eda3) | ![Screenshot 2023-07-28 at 6 58 31 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/12dadba2-80be-4aad-9fdd-b65123ac920f) | 

Now once you change the value in to `initialValue` in `useState` of `useLocalStrage`(using patch proposed in #340 ) here -> https://github.com/scaffold-eth/scaffold-eth-2/blob/296cc41aba37cf33a4f07fc17c41d177c3abe118/packages/nextjs/hooks/scaffold-eth/useLocalStorage.ts#L34

We have auto connect broken but now the debug contracts page works nicely 

----

### Some Solutions : 
1. Patch `useLocalStorage` in such way that it handle's both cases nicely (I tried doing but it was kindof out my mind to think and handle cases but need to spend more time figuring out ) 
2. Keep everything as it is and create wrapper's around hooks as suggested by Rinnat in (https://github.com/scaffold-eth/scaffold-eth-2/issues/453#issuecomment-1655001595) ( If it was only hook `useAccount` then this solution seem feasible but I see others breaks too like `useNetwork` ) 
3. Use hacky solution propose in #458 
4. Please feel free to suggest any other better solution if they come to your mind 🙌

**Comment by rin-st** [comment]
Gj Shiv!

I think custom solutions like `useAutoConnect` can work differently than `wagmi`s `autoConnect` option, because we don't know if there are edge cases or something we don't count. Additionally it adds some complexity. Also, we should avoid hacky solutions because again it becomes difficult to debug.

I think you have already seen this https://github.com/wagmi-dev/wagmi/issues/542 . There is no official solution, they propose to use `useMounted` for the full app or everywhere where hooks are used, and some people propose something like custom `useAutoConnect`.

I think the easiest way is to use a wrapper for every broken hook because it's easy to understand and maintain, it doesn't break `wagmi`s autoconnect. Don't know why no one proposed it :)

Something like this
```
import { useEffect, useState } from "react";
import { useAccount } from "wagmi";

export function useMountedAccount(...args: Parameters<typeof useAccount>) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const useAccountRes = useAccount(...args);

  return mounted ? useAccountRes : ({} as ReturnType<typeof useAccount>);
}
```

please lmk if I don't consider something and let's see what others think

**Comment by technophile-04** [comment]
> values in useAccount() that shouldn't be falsy on the first render, but in my hook everything is undefined, so it can cause bugs. I can write default values but again it's very difficult to maintain.

Ohh yeah this makes sense and yup it will be hard to maintain also we will be needing to do same for other breaking hooks too, lol It didn't come to my mind until you mentioned 🙌

> I think custom solutions like useAutoConnect can work differently than wagmis autoConnect option, because we don't know if there are edge cases or something we don't count. Additionally, it adds some complexity. Also, we should avoid hacky solutions because again it becomes difficult to debug.

Yup, I completely get this feeling!! and I agree it's not the best solution but since we have been using custom `useAutoConect` from the beginning of SE-2 and it was working fine there,  I have just copy pasted it and added a few lines in #458, yup and it was also suggested by Tmm here https://github.com/wagmi-dev/wagmi/issues/542#issuecomment-1436109311

Also, I have been taking a look at other protocols / SDK's docs and they suggest adding custom `useAutoConnect` for working nicely with them example checkout  [Safe apps sdk wagmi integration](https://github.com/safe-global/safe-apps-sdk/tree/main/packages/safe-apps-wagmi#integration-steps), I also remember one AA SDK doing similar

We can also mention about this in our SE-2 docs, saying we are using custom "useAutoConnect" to handle auto-connect and if you need any third-party integration which requires `useAutoConnect` you can add logic there  

---

Saying that it's great to keep an eye on https://github.com/wagmi-dev/wagmi/issues/542 because they said that they will internally handle this once NEXT.js 13 is stable enough 🙌 and also let's see what others have to tell 

But Thanks for the input and digging as always 🙌
