### ISSUE TITLE
Example UI: event section

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#466]
Let's keep expanding the Example UI with more examples.

In this case, show how the Event hooks (useScaffoldEventHistory.ts && useScaffoldEventSubscriber ) work. Right now it's just a console.log in `ContractData.tsx`

In `example-ui.tsx` we can add a new component `<ContractEvents>`, that show in two columns: Event History (history hook) / New Event (subscriber hook) info about the events from the contract: Address (so we can showcase the `<Address>` component) + Greeting + Value

We can ask Andrea if we need some help with the design

**Comment by rin-st** [comment]
Hey @carletex ! Could you ask Andrea for designs, please?

**Comment by ceeriil** [comment]
Hey @carletex any update yet?

**Comment by technophile-04** [comment]
Should we close since #576 ?
