### ISSUE TITLE
catch when user hasn't run yarn generate on foundry

### ISSUE THREAD

**Issue by austintgriffith** [scaffold-eth/scaffold-eth-2#468]
![files changed, compilation skipped](https://github.com/scaffold-eth/scaffold-eth-2/assets/2653167/673fde52-3493-4538-9079-548f48f90931)
****

you get this gnarly error when you haven't run yarn generate yet and you try to deploy

**Comment by technophile-04** [comment]
![258219613-76ac3221-e2b7-42ab-b878-ebddf863e203](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/a79047fc-60fe-48b2-b3c8-df0f9953f5f6)

We kindof added a better error message at #475 🙌

closing this for now 🙌
