### ISSUE TITLE
add gnosis chain as "gnosis" to networks in foundry

### ISSUE THREAD

**Issue by austintgriffith** [scaffold-eth/scaffold-eth-2#469]
add gnosis chain as "gnosis" to networks in foundry

and also "chiado"?

**Comment by technophile-04** [comment]
Added `gnosis` and `chiado` in `foundry.toml` 

Note : For chains that are not present in the foundry's [StdChain](https://github.com/foundry-rs/forge-std/blob/f18e8aa3e72eef83518766eb34ad8c8d8e2aa0aa/src/StdChains.sol#L186)  like `chiado` you need to do `exportDeployments("chiado")` check pt.5 of https://github.com/scaffold-eth/scaffold-eth-2/issues/470#issue-1832581912 we are trying to make it more dev friendly....but `gnosis` should work out of the box now 🙌

Closing this, Thanks 🙌
