### ISSUE TITLE
Making foundry stable 

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#470]
### Bugs noticed

1 . While doing `yarn deploy` I got this warning :

    > EIP-3855 is not supported in one or more of the RPCs used. Unsupported Chain IDs: 31337.
    > Contracts deployed with a Solidity version equal or higher than 0.8.20 might not work properly.
    > For more information, please see https://eips.ethereum.org/EIPS/eip-3855
    
    This might the reason why Austin said 0.8.20 was not working we should fix this

### Developer Experience :

1 . ~Lets have all contracts in `contracts` directory similar to `hardhat`~ (fixed at #471  )

2 . Lets add's intersection of all the networks present in `stdChains` & `hardhat.config.ts` default in `foundry.toml` 

3 . ~Let's add some comments so that the user does not delete out custom `exportDeploymentFunction`~ fixed at #406 
<details>
<summary>Sudo sample code</summary>

              function run() external {
                  uint256 deployerPrivateKey = setupLocalhostEnv();
            
                  vm.startBroadcast(deployerPrivateKey);
                  YourContract yourContract = new YourContract(
                      vm.addr(deployerPrivateKey)
                  );
                  console.logString(
                      string.concat(
                          "YourContract deployed at: ",
                          vm.toString(address(yourContract))
                      )
                  );
                  vm.stopBroadcast();
              
                   /**
                   * This function generates the file containing the contracts Abi definitions.
                   * These definitions are used to derive the types needed in the custom scaffold-eth hooks, for example.
                   * This function should be called last.
                   */
                   exportDeployments();
          
                  // If your chain is not present in foundry's stdChain, then you need to call function with chainName:
                  // exportDeployments("chiado")
      
             }
             

      
</details>

4 . Checkout Austin's issue here -> #468
Possible solution: Since we are inheriting from `ScaffoldETHDeploy` contract can we add nice checks in 
`ScaffoldETHDeploy` contract's `constructor` like checking `deployerKey` etc and will  using `revert`show nice error ? 
     
        
Also regarding this line :

```solidity
uint256 deployerPrivateKey = setupLocalhostEnv();
```

Maybe we can set a public variable in the `ScaffoldETHDeploy` contract named `envDeployerKey` and people who 
extend `ScaffoldETHDeploy` will have access to this.

5 . ~We recently added another utility similar to `exportDeployments` i.e you can now pass optional `networkName` : `exportDeployments("networkName")` this allows users to add `chains` eg: `chiado` which are not present in foundry's [`StdChain`](https://github.com/foundry-rs/forge-std/blob/f18e8aa3e72eef83518766eb34ad8c8d8e2aa0aa/src/StdChains.sol#L186) and generate abi definations for frontend without breaking~.

~Although this is a nice hack for now we should probably update it soon, let's find a way better way for this 🙌 such that user just need to define it in `foundry.toml` and just calling `exportDeployments()` without `networkName` does the job 🙌~ Fixed at #475 

6 . ~Get the deploy command similar to `hardaht` : `yarn deploy --network network_name`, this can maybe also help in pt.5 if there is way in foundry to access passed in flags cc @jrcarlos2000~  - Fixed at #475

**Comment by jrcarlos2000** [comment]
> Lets add's intersection of all the networks present in stdChains & hardhat.config.ts default in foundry.toml

does this mean listing all the networks in `stdChains` inside  `foundry.toml`

>Get the deploy command similar to hardaht : yarn deploy --network network_name, this can maybe also help in pt.5 if there is way in foundry to access passed in flags.

for now i suggest passing $1 inside the package.json, this will require user to pass `yarn deploy --network {network_name}` and catch {network_name} as $1. 

>Possible solution: Since we are inheriting from ScaffoldETHDeploy contract can we add nice checks in
ScaffoldETHDeploy contract's constructor like checking deployerKey etc and will using revertshow nice error ?

Adding a readable revert message

**Comment by jrcarlos2000** [comment]
When running a local node, there are default accounts generated with `yarn chain` , what if a user wants to use a custom `DEPLOYER_PRIVATE_KEY` , what should be the priority when choosing the account to execute transactions from ? 

Should it be :
1) the .env `DEPLOYER_PRIVATE_KEY` 
2) the default accounts from `yarn chain`

cc: @technophile-04 @carletex

**Comment by technophile-04** [comment]
>  if a user has the .env deployer key set for other networks and suddenly wants to run on localhost, it would fail bcs is not funded.

Ohh yes yes sorry my bad, I think the current situation is ok 🙌

**Comment by technophile-04** [comment]
### Developer Exp : 

Currently  in `hardhat` we have this workflow for verifying the contract : 

![Screenshot 2023-08-12 at 9 13 21 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/9ef1db09-8d6e-4d64-ad26-41f527ee3191)

But in `foundry` you have to do `yarn deploy:verify --network sepolia`, there is no command like `yarn verify` which let's you verify contrract after deployments 

Also if `yarn deploy:verify` fails this won't generate `deployedContract.ts` in `frontend` even though the contract is deployed but verification failed 

Lets try to get this command also similar to `yarn verfiy` as `hardhat` 🙌

**Comment by jrcarlos2000** [comment]
I have been exploring the possibility to replicate things like `yarn deploy:verify --network sepolia` but havent found a way yet. So far seems like writing a script would do the work because in forge there is only one command `forge verify-contract` which will do a verification for a single contract.

**Comment by technophile-04** [comment]
We need to `--chain-id 31337` in `fork` package.json script : 
https://github.com/scaffold-eth/scaffold-eth-2/blob/e979ab45b13af7af69b35ea51cac98f64b68464b/packages/foundry/package.json#L7C2-L7C2

Check out this comment : https://github.com/scaffold-eth/scaffold-eth-2/issues/524#issuecomment-1714558947

Also maybe add a note in docs because if people use normal fork without mentioning `--chaind-id 31337` anvil uses chain-id of forked chain and in frontend this causes issues as mentioned in #524

**Comment by technophile-04** [comment]
Closing this for now I think we have accomplished basic stuff lets create new issues as we find them, thanks 🙌
