### ISSUE TITLE
CLI: README improvements

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/scaffold-eth-2#472]
After we set an initial version of the README for CLI and Foundry (`cli` branch) with #442, would be nice to add a few more sections to it:

- [ ] Add arguments explanations (projectName, --install .. )
- [x] Adapt guide of how to contribute, explaining how to set the environment in local to test changes on the CLI

**Comment by technophile-04** [comment]
Completed in #422, We can create a new issue soon on point 1. once we maybe get CLI branch in new repo 🙌
