### ISSUE TITLE
UI: Footer misalignment for small screens(mobile)

### ISSUE THREAD

**Issue by 0xChijoke** [scaffold-eth/scaffold-eth-2#497]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

When deploying a fresh Scaffold-ETH 2 build, I've noticed that the footer on mobile devices appears misaligned and is positioned to the left. This behaviour seems unintended and could potentially be considered a bug.

![photo_2](https://github.com/scaffold-eth/scaffold-eth-2/assets/53488449/3caf2ca6-c97b-4dde-b39e-5e9b5a45d575)

It's a small change but will ensure builders have fewer UI issues to fix when shipping.

Also tried to create a PR to suggest a fix but couldn't get around the permissions as I have an existing SE2 fork and am not able to make a branch.

### Expected Behavior

Everything should remain in a straight line.

![photo](https://github.com/scaffold-eth/scaffold-eth-2/assets/53488449/9e9a24ed-3eee-4c4c-a393-4cac4e20ff64)

### Steps To Reproduce

Use a responsive design tool to check the footer of an SE2 build for a small screen.

### Anything else?

A change that worked was adding "flex item-center"

         <div className="flex items-center">
              Built with <HeartIcon className="inline-block h-4 w-4" /> at 🏰{" "}
              <a
                href="https://buidlguidl.com/"
                target="_blank"
                rel="noreferrer"
                className="underline underline-offset-2"
              >
                BuidlGuidl
              </a>
            </div>

**Comment by technophile-04** [comment]
Tysm @0xChijoke, Please feel free to create PR 🙌

**Comment by 0xChijoke** [comment]
I tried but the permissions are blocking from pushing a local branch.

**Comment by technophile-04** [comment]
You can fork the repo and create PR, checkout the “Pull Requests” section of [CONTRIBUTING.md](https://github.com/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md#pull-requests)
