### ISSUE TITLE
Minor readme tweaks

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#508]
### 1. Mentioning about custom hooks: 

Since we have minimized the README a bit, we lost the mentions of custom hooks in readme which is also a kind of main feature of SE-2

Previously we had `Contents` section in the readme so people could easily notice it, but since we have removed it there is no mention about custom hooks 

**Idea** : We can probably add a 4th point here : 
![Screenshot 2023-08-28 at 11 56 57 AM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/12d2e8af-f011-4e11-ae36-2e3ca1f4f87c)

Maybe `Custom hook & useful components` (lol we should update words) and in its descriptions we can link hooks sections of docs

### 2. Mentioning CLI at the bottom: 

Since we have updated the CLI README nicely, We can tell people that they can look at [CLI README](https://github.com/scaffold-eth/scaffold-eth-2/tree/cli#quickstart) for basic docs or maybe point them directly to `npx` section of docs once we are ready with https://github.com/scaffold-eth/se2-docs/pull/16 🙌, and maybe also mention that it's under active development and been worked upon at #413 PR

But would love to hear others idea's / thoughts as well 🙌

**Comment by edakturk14** [comment]
1. I like the idea to add a forth point, what do you think of this: 

- 🪝 **[Custom Hooks](https://docs.scaffoldeth.io/hooks/)**: Collection of React hooks to simplify interactions with deployed smart contracts

2. Once we merge the PR over [here](https://github.com/scaffold-eth/se2-docs/pull/16), similarly can update the main readme

Thank you Shiv!!

**Comment by technophile-04** [comment]
> 🪝 [Custom Hooks](https://docs.scaffoldeth.io/hooks/): Collection of React hooks to simplify interactions with deployed smart contracts

I like this !! 

Nitpick: Can we squeeze in `wagmi` in b/w this sentence like maybe "...React hooks wrapper around wagmi..."

Reason: I have seen that past people who used SE-1 has wrong notion when then come to SE-2 that we still use `eth-hooks` and also for new people who will be trying SE-2 may feel at home by seeing the word wagmi 😅

> Once we merge the PR over https://github.com/scaffold-eth/se2-docs/pull/16, similarly can update the main readme

Yup !

Tysm Eda 🙌 !!

**Comment by edakturk14** [comment]
oh thats a great point, yeah makes a lot of sense to me!! 

ı like the way you put it, please feel free to modify as well 

- 🪝 **[Custom Hooks](https://docs.scaffoldeth.io/hooks/)**: Collection of React hooks wrapper around wagmi to simplify interactions with deployed smart contracts
