### ISSUE TITLE
bug: Input receive wrong bytes32 from string

### ISSUE THREAD

**Issue by cauta** [scaffold-eth/scaffold-eth-2#513]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

i have a contract function that receive input from bytes32.  
after input a hex string, seem like they receive string instead of bytes32.    
<img width="393" alt="image" src="https://github.com/scaffold-eth/scaffold-eth-2/assets/15400058/0cc477f9-2e49-4a9f-b451-6d19ef34b2dd">

### Expected Behavior

input receive should convert to bytes32 format

**Comment by technophile-04** [comment]
Hey @cauta, it seem that you are trying to append `0X` instead of `0x`, could you try with small `x`

**Comment by cauta** [comment]
You’re right. I missed that auto uppercase . Can close this issue. Thanks
