### ISSUE TITLE
Migrate to NextJS App router

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#526]
I tried it when we migrated to NextJS v13, but it was in beta and I was getting a bunch hard-to-debug errors. It seems more stable now.

It's the path they are taking, so I think we should migrate to be able (us & builders) to use the current features (client / server components, server actions, etc) and future ones.

https://nextjs.org/docs/app
Upgrade pages => app router: https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration

What do you all think?

**Comment by Anurag-Raut** [comment]
I was migrating my personal project which is using scaffold-eth-2 , thought i could help migrate scaffold-eth-2 as well.

If anyone else isn't working on it , can I ?

**Comment by carletex** [comment]
Sure @Anurag-Raut !

Feel free to draft a PR when ready.

Thanks!! <3

**Comment by Anurag-Raut** [comment]
@carletex we are currently using next v13.1.16 ,should we upgrade to next v13.4 since app router has became stable from v13.4

also if we decided to stick with the current version of next we would need to use app Router in experimental mode in v13.1.16
