### ISSUE TITLE
yarn deploy: Discovered incompatible solidity versions

### ISSUE THREAD

**Issue by abhilashi** [scaffold-eth/scaffold-eth-2#530]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

yarn deploy

[⠃] Compiling...2023-09-10T05:53:03.784634Z ERROR ethers_solc::resolver: failed to resolve versions
[⠊] Compiling...
Error: 
Discovered incompatible solidity versions in following
: script/Deploy.s.sol (^0.8.19) imports:
    contracts/YourContract.sol (>=0.8.0 <0.9.0)
    script/DeployHelpers.s.sol (^0.8.19)
    lib/forge-std/src/console.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/Script.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/console.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/console2.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/safeconsole.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdChains.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdCheats.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdJson.sol (>=0.6.0 <0.9.0)
    lib/forge-std/src/StdMath.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStorage.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStyle.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/StdUtils.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Base.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStorage.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/console2.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/interfaces/IMulticall3.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStorage.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
Discovered incompatible solidity versions in following
: script/DeployHelpers.s.sol (^0.8.19) imports:
    lib/forge-std/src/Script.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/console.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/console2.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/safeconsole.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdChains.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdCheats.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdJson.sol (>=0.6.0 <0.9.0)
    lib/forge-std/src/StdMath.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStorage.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStyle.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/StdUtils.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Base.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStorage.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/console2.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/interfaces/IMulticall3.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStorage.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
Discovered incompatible solidity versions in following
: script/VerifyAll.s.sol (^0.8.19) imports:
    lib/forge-std/src/Script.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/solidity-bytes-utils/contracts/BytesLib.sol (>=0.8.0 <0.9.0)
    lib/forge-std/src/console.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/console2.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/safeconsole.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdChains.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdCheats.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdJson.sol (>=0.6.0 <0.9.0)
    lib/forge-std/src/StdMath.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStorage.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStyle.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/StdUtils.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Base.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStorage.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/console2.sol (>=0.4.22 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/interfaces/IMulticall3.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/StdStorage.sol (>=0.6.2 <0.9.0)
    lib/forge-std/src/Vm.sol (>=0.6.2 <0.9.0)

### Expected Behavior

Compiled.

### Steps To Reproduce

npx create-eth@latest

yarn chain
yarn deploy

**Comment by technophile-04** [comment]
@abhilashi  could run : 

```shell
foundryup
```

so that you get latest version of everything and then try again ? 

Also, what OS are you using? 


I just checked on Mac OS and it seems to work fine there
