### ISSUE TITLE
bug: Issue with solidity version update to 0.8.21

### ISSUE THREAD

**Issue by VlodkoMr** [scaffold-eth/scaffold-eth-2#539]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

Changed solidity version in hardhat config and smart-contract to:
`pragma solidity 0.8.21;`

Compilation success, but on default deployment script (00_deploy_your_contract.ts) return an error:

_An unexpected error occurred:
Error: ERROR processing /packages/hardhat/deploy/00_deploy_your_contract.ts:
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="Error: Transaction reverted and Hardhat couldn't infer the reason.",_

### Expected Behavior

Expected success deployment.

### Steps To Reproduce

Clone scaffold-eth repo, change solidity version to 0.8.21, try to deploy smart-contract.

**Comment by technophile-04** [comment]
Thanks for reporting this, Should be fixed by #546 🙌
