### ISSUE TITLE
Hardhat ethers => Hardhat viem

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#567]
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/2486142/cfa67d2b-ddd2-4cb8-a51a-2f2208efe72f)
https://twitter.com/HardhatHQ/status/1712126192935985312

---

Since we are already using `viem` on the NextJS package, I think, for consistency, we should move the Hardhat package to use `viem` too.

**Comment by carletex** [comment]
ofc @rin-st !!

I assigned it to you, but anytime feel free to assign it to yourself!

**Comment by rin-st** [comment]
@carletex @technophile-04 should we close this for the [same reason](https://github.com/scaffold-eth/scaffold-eth-2/issues/632#issuecomment-2072354741)? And because I didn't find working solution for now too 😄

**Comment by carletex** [comment]
Yep yep! We can always come back to this if needed.
