### ISSUE TITLE
Update CLI Readme

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#573]
The README in the CLI still has the long version / no linking to SE2 docs.

Let's use the one we have in main (tweaking as necesary for CLI use)

**Comment by Pabl0cks** [comment]
Working on this 🙌 

I think I will also update SE2 docs to add all the Fountry references. Since we're already offering the [Beta] CLI installation at Docs, I think it can make sense to have all the Fountry explanations too.
