### ISSUE TITLE
(Re)move Example UI

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#576]
Following feedback from some people and for the sake of keeping the codebase lighter, let's discuss what we can do with Example UI.

The idea behind it was to show beginners how to use SE2 (components, hooks, styling, etc), but I don't think it has been very useful for that purpose. Also, types break the moment you start tweaking the contract, and it's something you have to remove when deploying.

I see a couple of options:

1. Remove it completely and create a good Recipes section in the SE-2 docs, where people can copy-paste examples that work out of the box. This is what most libraries/starter kits do. I already created the issue: https://github.com/scaffold-eth/se2-docs/issues/25, since the "Recipes" section is something that we wanted to do anyway.
2. Add it in as an extension for the CLI. People could opt in if they want. "Would you like an example UI that shows how to style and use hooks?"

My vote is **1**, since I don't like cluttering the CLI options with this, something that I feel it's not that important / useful.

Let's hear what you all think!

**Comment by damianmarti** [comment]
Option 1 sounds good to me too!

**Comment by technophile-04** [comment]
> Also, types break the moment you start tweaking the contract, and it's something you have to remove when deploying.

Ohh yeah that's another problem :( 

Yup even I like 1st option 🙌
