### ISSUE TITLE
Consistency codebase refactor

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#617]
Let's do some refactoring to have a more consistent codebase:

- [x] It seems that we are more inclined to use types without `T` prefix. Let's unify for consistency. https://github.com/scaffold-eth/scaffold-eth-2/pull/627
- [x] `0x${string}` to viem's `Address`? [WIP @sverps ]
- [x] TS: interfaces -> types https://github.com/scaffold-eth/scaffold-eth-2/pull/627
- [ ] JSDoc tweaks: see https://github.com/scaffold-eth/scaffold-eth-2/pull/627#issuecomment-1828163974

Check TS guide: https://github.com/scaffold-eth/scaffold-eth-2/issues/232

What else? cc @technophile-04 @rin-st @sverps

**Comment by rin-st** [comment]
- TS: interfaces -> types
- [components/scaffold-eth/Contract](https://github.com/scaffold-eth/scaffold-eth-2/tree/main/packages/nextjs/components/scaffold-eth/Contract) utilsContract.tsx, utilsDisplay.tsx -> utils.ts. Also refactor it, for example move `getParsedError` to `utils/scaffold-eth`
- remove barrels?)

**Comment by carletex** [comment]
Updated OP with new stuff. Also opened #627 

I also think we should have all the desired consistency documented up somewhere (with conclusions from https://github.com/scaffold-eth/scaffold-eth-2/issues/232 too).

Not sure where the best place could be: Github wiki? SE-2 docs -> contributing?

---

> remove barrels?

Yep, this is an interesting discussion too. I remember seeing some issues in the NextJS 14 migration with HMR.

**Comment by technophile-04** [comment]
> Not sure where the best place could be: Github wiki? SE-2 docs -> contributing?

Didn't knew about Github Wiki! I think it looks a fare place 🙌


> > remove barrels?
> 
> Yep, this is an interesting discussion too. I remember seeing some issues in the NextJS 14 migration with HMR.

I am kind of 60%(remvoing barrels) and 40% keeping them because I think in new Next version there is option to mark barrels file and optimize them => https://vercel.com/blog/how-we-optimized-package-imports-in-next-js but don't know if it actually work and 100% assured solution will be removing barrels files

> - [ ] JSDoc tweaks: see https://github.com/scaffold-eth/scaffold-eth-2/pull/627#issuecomment-1828163974

Is anybody already working on this TODO ? Would love to tackle it 🙌

**Comment by sverps** [comment]
I'm picking up the address type stuff
