### ISSUE TITLE
Error HH8: There's one or more errors in your config file:

### ISSUE THREAD

**Issue by SvenMeyer** [scaffold-eth/scaffold-eth-2#625]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

When following along as described in the `README.md`, I get ...
```
$ yarn chain
Error HH8: There's one or more errors in your config file:

  * Invalid account: #0 for network: mainnet - private key too short, expected 32 bytes
  * Invalid account: #0 for network: sepolia - private key too short, expected 32 bytes
  * Invalid account: #0 for network: goerli - private key too short, expected 32 bytes
  * Invalid account: #0 for network: arbitrum - private key too short, expected 32 bytes
  * Invalid account: #0 for network: arbitrumGoerli - private key too short, expected 32 bytes
  * Invalid account: #0 for network: optimism - private key too short, expected 32 bytes
  * Invalid account: #0 for network: optimismGoerli - private key too short, expected 32 bytes
  * Invalid account: #0 for network: polygon - private key too short, expected 32 bytes
  * Invalid account: #0 for network: polygonMumbai - private key too short, expected 32 bytes
  * Invalid account: #0 for network: polygonZkEvm - private key too short, expected 32 bytes
  * Invalid account: #0 for network: polygonZkEvmTestnet - private key too short, expected 32 bytes
  * Invalid account: #0 for network: zkSyncTestnet - private key too short, expected 32 bytes
  * Invalid account: #0 for network: zkSync - private key too short, expected 32 bytes
  * Invalid account: #0 for network: gnosis - private key too short, expected 32 bytes
  * Invalid account: #0 for network: chiado - private key too short, expected 32 bytes
  * Invalid account: #0 for network: base - private key too short, expected 32 bytes
  * Invalid account: #0 for network: baseGoerli - private key too short, expected 32 bytes
  * Invalid account: #0 for network: scrollSepolia - private key too short, expected 32 bytes
  * Invalid account: #0 for network: scroll - private key too short, expected 32 bytes

To learn more about Hardhat's configuration, please go to https://hardhat.org/config/

For more info go to https://hardhat.org/HH8 or run Hardhat with --show-stack-traces
```

### Expected Behavior

should start hardhat dev node

### Steps To Reproduce

$ yarn install
$ yarn chain

**Comment by technophile-04** [comment]
Hey @SvenMeyer, It seems like you don't have a valid private key in `.env` or you have by mistake edited the hardhat 0th account  private key here : 
https://github.com/scaffold-eth/scaffold-eth-2/blob/c3344b3d907953cd2fad24a7911e7fade01242e0/packages/hardhat/hardhat.config.ts#L14

Also PS : Ideally instead of copy-pasting your own private-key to `.env`  we recommend doing [`yarn generate`](https://docs.scaffoldeth.io/deploying/deploy-smart-contracts#2-generate-a-new-account-or-add-one-to-deploy-the-contracts-from) instead

**Comment by SvenMeyer** [comment]
@technophile-04 Ok, thanks. Nowhere in the `README.md` it said that I have to set a PK (some)where ...

**Comment by technophile-04** [comment]
> Nowhere in the README.md it said that I have to set a PK (some)where ...

You actually don't need to set PK before running `yarn chain`, Did you get this error on running a fresh clone of the repo?

**Comment by SvenMeyer** [comment]
yes

**Comment by technophile-04** [comment]
Strange, I just tried on fresh clone and followed steps mentioned here : https://github.com/scaffold-eth/scaffold-eth-2#quickstart

Its all working for me, would be really great if you could pass the repo link where this error is happening to you

**Comment by technophile-04** [comment]
> https://github.com/SvenMeyer/scaffold-eth-2-test-1

Its nicely working for me here too on fresh clone. 

Don't why its happening with you, maybe there's `env` variable set in your terminal with same name as SE-2 `DEPLOYER_PRIVATE_KEY ` , try removing it once on linux you could do : 

```shell
unset -f DEPLOYER_PRIVATE_KEY 
```

Also I am assuming you are not adding any `.env`  in `pacakges/hardhat`  file initially (on fresh clone) while running `yarn chain`

**Comment by SvenMeyer** [comment]
Did not change a thing ...

However just had a quick look at `hardhat.config.ts` ... maybe the `??` should be `||` here ? 

https://github.com/scaffold-eth/scaffold-eth-2/blob/b2a91b8304fefd72fa68a5fe972d1f91525280eb/packages/hardhat/hardhat.config.ts#L14

At least it works once I have done that ;-)

**Comment by carletex** [comment]
> maybe the ?? should be || here ?

It's basically the same thing, but `||` is broader (falsy value, instead of just `undefined` or `null` as `??`)

What is happening is that you have an invalid (or empty string) `DEPLOYER_PRIVATE_KEY` somewhere. It could be that you have created an empty `.env` file like:

```
DEPLOYER_PRIVATE_KEY=
```

or you have it in your OS.

For futher debugging you can do what @technophile-04 is suggesting. You can also add:

```
console.log("deployer key type", typeof deployerPrivateKey);
console.log("deployer key length", deployerPrivateKey.length);
```
in your `hardhat.config.ts` file and post the results here

**Comment by technophile-04** [comment]
Awesome ! 

> ... and all the Some peer dependencies are incorrectly met messages I can simply ignore ?

Yeah for now ignore it, but everything should fine 🙌
