### ISSUE TITLE
bug: `useScaffoldEventHistory` is throwing type errors for `filters´ parameter when using it on external contracts

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/scaffold-eth-2#631]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

When I try to use `filters` parameter on `useScaffoldEventHistory` hook, is not working well for the contract I defined in `externalContracts.ts`.

Trying the same hook with a deployed contract, `filters` is working as intended without `type` errors.

### Expected Behavior

When using `filters` parameter on `useScaffoldEventHistory` hook it should filter the events received, only fetching those that match the parameter you are filtering by.

### Steps To Reproduce

- Add the external contract ABI to `externalContracts.ts`. Can copy and paste the code from this [gist](https://gist.github.com/Pabl0cks/838fd14baee0b3cedfc581cacb1d18a0) replacing your `externalContracts.ts` current code.
- Set the network to Sepolia in `scaffold.config.ts` and `hardhat.config.ts`.
- Try to use useScaffoldEventHistory hook on `index.tsx`. 
    <details>
    <summary>
    Can add this code to your `index.tsx`: 
    </summary>
    
    ```tsx
      import { useScaffoldEventHistory } from "~~/hooks/scaffold-eth";

      const { data: events, isLoading: isLoadingEvents } = useScaffoldEventHistory({
        contractName: "BatchRegistry",
        eventName: "CheckedIn",
        fromBlock: 4785545n,
        filters: { first: true },
        blockData: true,
        transactionData: true,
        receiptData: true,
      });
    ```
    
    </details>
    
With those steps, VSCode shows me a type error similar to this one:

"_The type '{ first: true; }' is not assignable to type 'undefined'. ts(2322) contract.ts(238, 3): The expected type comes from property 'filters', which is declared here on type 'UseScaffoldEventHistoryConfig<"BatchRegistry", "CheckedIn", true, true, true>'_"

**Comment by carletex** [comment]
@sverps Can you take this when you have time?

**Comment by sverps** [comment]
Hey @Pabl0cks, I finally had some time to look into this. The event param on which you're trying to filter is not indexed, so filtering on it is [not supported](https://viem.sh/docs/actions/public/getLogs.html#arguments). That's why the type info shows an error when you try and pass in this filter. With how the contract is setup, filter can only be `undefined`, since none of the params are indexed.

To filter on non-indexed params, you would need to manually parse and filter the logs after retrieving them.

**Comment by Pabl0cks** [comment]
Thanks a lot @sverps for digging into it! 🙌
