### ISSUE TITLE
Better placement for switch networks button 

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#634]
### Description : 
The OG discussion was [here](https://github.com/scaffold-eth/scaffold-eth-2/pull/615#discussion_r1400301648) 

But here are some of the options that we discussed : 

1.  Similar to Uniswap : 
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/2486142/1241a815-0f40-483a-830a-7753d878dbcd)
Disadvantages: It will be hard to configure logos for all chains. (What if instead of logo we used initial 2 chars of chain name ? )

2.  Having a down arrow (▼) next to the name that opens a dropdown (when multiple chains configured?)
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/2486142/69a924d9-215e-4a03-a458-44edc8d2a4ab).
Disadvantages:  Hitbox would be very small. On top of that, it would be too close to hitbox of the the balance toggle and (especially on mobile) might be annoying to not be able to hit it reliably

3. Having `Switch network` button at footer : 
![Screenshot 2023-11-21 at 5 59 36 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/05ee05ea-7983-4267-8aa8-865c04842cd8)
Disadvantages: Its too far from actual wallet stuff and maybe kind of non-intuitive for users. 

4. Keep it as it is (which we have currently in `main`) : 
![Screenshot 2023-11-30 at 4 15 26 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/d774c553-02ca-4398-b838-08a5b3c37b73)
Disadvantages: It is kind of hidden now. 

### My thoughts : 

I like option 2. and option 1. 

Option 2. : I think maybe if we increase a bit `space-y` b/w Balance and Chain dropdown and slightly increase font of Chain dropdown both on desktop nd mobile it should fit well. 

But would love to know other thoughts ! 🙌

**Comment by carletex** [comment]
I proposed option 2 because it seemed the most straight & clear way to do it without making big changes. Maybe some extra Y space + `text-sm` (instead of `text-sm`) could work. 

But I think that the current version is also OK. It's next to other wallet actions. Yep, it's a bit hidden, so I guess it comes to how much you want to show that your dApp supports multiple chains :D

But we could test different options and ask for feedback!

**Comment by rin-st** [comment]
I think that option 2 is the best, too. Probably it's worth to make chain text bolder to make it more notable

> Yep, it's a bit hidden, so I guess it comes to how much you want to show that your dApp supports multiple chains :D

Not sure if someone wants to hide additional functionality of the app :D

**Comment by damianmarti** [comment]
I like option 1! 

Maybe the user can configure if only the logo or initials from the chain name or the full chain name are shown.

**Comment by Pabl0cks** [comment]
I like option 2 with the styling tweaks to make it easier to read and click. Seems like a good first approach, users are familiar having the network there, and with the arrow icon it will be intuitive for them.

Option 1 is cool also, but maybe we can iterate to it in the future if it establishes as a standard for most dapps. 
Right now some multichain dapps show logo + name (sushi), others even change the network when you do so in your wallet (hop), so we could wait a bit and see which one becomes the standard.

**Comment by KcPele** [comment]
I like option 1
there are endpoints we can call that will get us the logos of any chain it supports and then we can display them, or we can hard code them for now and combine them with wagmi
![Screenshot from 2023-12-28 08-42-59](https://github.com/scaffold-eth/scaffold-eth-2/assets/64108987/025d5683-8eff-4bca-8035-bc619d2084be)

**Comment by KENILSHAHH** [comment]
For option 1, do we need to hard code the logos for different chains as of now?

**Comment by technophile-04** [comment]
Closing this for now, I think current version just works fine but we can always re-open / create new issue if we find better / easy way of handling this 🙌
