### ISSUE TITLE
bug: broken `scaffold.config.ts` for `targetNetwork` other than `hardhat / foundry`

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#640]
### Description

If you put chains other than `hardhat` inside `targetNetwork` or have more than 1 length we get this error : 

![Screenshot 2023-12-03 at 5 37 34 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/371dabc4-6401-4036-9e68-5d3c5f3d4caf)

Full error : `1. 'scaffoldConfig' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer. [7022]`

This was introduced in #630, after a lot of digging it seems that it is caused because we are importing `scaffoldConfig` inside `abi.d.ts` file. I think because `.d.ts` is kind of a global file maybe because of it this is caused but not completely sure but maybe @sverps has a better explanation and a solution too 🙌  

Like after removing the import of scaffoldConfig the error is gone.

**Comment by sverps** [comment]
I'll look into it, weird

**Comment by technophile-04** [comment]
Closing this 🙌 Since I think we agreed upon adding just the documentation for it, summary in this comment https://github.com/scaffold-eth/scaffold-eth-2/pull/641#discussion_r1415184004
