### ISSUE TITLE
Polling interval difference per network

### ISSUE THREAD

**Issue by wbt** [scaffold-eth/scaffold-eth-2#646]
- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

First, big thanks to @sverps and @blahkheart for #615! This responds to a comment from that as a new issue, instead of discussing further improvement on that closed PR. 
> * When multiple networks configured, pollingInterval will for all networks be the one from the config (if anyone has an idea to keep polling interval to 4000 while on hardhat, while at the same time use a slower polling for other networks, let me know)

https://github.com/scaffold-eth/scaffold-eth-2/pull/615#issuecomment-1820639836 says this is OK as the config files can differ on dev machines, but we can do better and allow more similarity in dev/prod environments (which is good as a matter of practice).

It seems like the best way to do this would be to add an optional pollingInterval property to the chain configuration, perhaps even to the RPC endpoint configuration, and if the property isn't there, fall back to the default in the overall config file.  I would then set the default in the config file to a fairly high value and put a lower starting value in there for Hardhat specifically in its chain-specific configuration.

**Comment by sverps** [comment]
The main issue I came across was that the `pollingInterval` is a common config when creating the available app chains with wagmi`s `configureChains` in `wagmiConnectors`, so there doesn't seem to be a mechanism to pass different polling intervals based on chain there.

So unless there's a simple way to do it that I didn't find, I'm afraid a solution to provide this (by recreating the whole wagmi config on network switch and putting it in some global context or so) might get too complex considering the benefit it would bring.

**Comment by technophile-04** [comment]
Hey thanks @wbt for suggestion 🙌

Completely agree with Samuel, I think it would be great if its handled on the wagmi side rather than creating a workaround / patchy solution in SE-2 

Btw, In Wagmi V2 I think they are planning to allow to configure `pollingInterval` on per chain basis: https://beta.wagmi.sh/react/api/createConfig#pollinginterval

Lets wait until main version of Wagmi V2, closing this for now thanks 🙌
