### ISSUE TITLE
Prop to configure default mode for `EtherInput` & `Balance` component

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#677]
### Description

Currently `EtherInput` & `Balance` components both by default show ethers value and there's no prop to configure that behaviour

It would be great to let the developer also configure this default behavior, Like if he wants to show dollar value by default (on initlal load)

Maybe something like : 

```tsx
<Balance usdMode />
```

Similar for `EtherInput`, we should keep `usdMode` as optional if its not passed we could render ethers values as previous setup

**Comment by MukulKolpe** [comment]
Hey @technophile-04, can I work on this issue?

**Comment by carletex** [comment]
Go for it @MukulKolpe ! Assigned it to you. Thanks ;)
