### ISSUE TITLE
Wagmi V2

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#678]
### Description : 

Wagmi V2 was [just announced](https://x.com/wevm_dev/status/1742991699842916629?s=20) along with viem v2,  checkout new wagmi docs https://wagmi.sh , viem docs https://viem.sh

We are planning to merge #526 next week if everything works fine. This will also let Wagmi release a few minor/patch releases by then because it seems too fresh for now. 

After #526 is merged, planning to work on this but we can always collaborate as we did in V1 migration #352 🙌

**Comment by KcPele** [comment]
I am very much interested and ready to join when it is time to collaborate

**Comment by technophile-04** [comment]
> I am very much interested and ready to join when it is time to collaborate

Really sorry just saw this 

> After https://github.com/scaffold-eth/scaffold-eth-2/issues/526 is merged, planning to work on this but we can always collaborate as we did in V1 migration https://github.com/scaffold-eth/scaffold-eth-2/pull/352 🙌

Just to be clear similar to #352 would love if any of core* contributors wants to collaborate due to their overall context to SE-2 and there seems alot of breaking changes in migration
