### ISSUE TITLE
lint-warning:  Props must be serializable for components in the "use client" entry file, "onChange" is invalid

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#686]
### Description : 

Noticed this warning when you go to `EtherInput` or `IntegerInput` / other files which has `use client` on top and uses `onChange` as prop example : 

![Screenshot 2024-01-15 at 11 58 25 AM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/556dba8f-ad4f-427e-aeed-f3d985078487)

Related discussion : 

https://github.com/vercel/next.js/discussions/46795

**Comment by KcPele** [comment]
The solution is to remove "use client" from the child which is in EtherInpute, IntergerInput and AddressInput.tsx

**Comment by KcPele** [comment]
i am currently removing it

**Comment by technophile-04** [comment]
completed at #688
