### ISSUE TITLE
Remove `useAccountBalance` hook

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#687]
### Description : 

If we look at things returned by `useAccountBalance` they are maniy  
1. `balance` => which is same as `balance.formated` from wagmi's [`useBalance`](https://1.x.wagmi.sh/react/hooks/useBalance) hook
2. `price` => it can be easily accesed by global state `useGlobalState(state => state.nativeCurrencyPrice)`
3. `onToggleBalance` this function was just toggling boolean value and not actual balance, we are also no more using this function anywhere after #683 
4. `isError`, `isLoading` again this are from  wagmi's `useBalance` hook

So think maybe we could remove this, but would love to hear others thoughts, other option might be adding more functionality to it instead of removing

**Comment by Hotmanics** [comment]
Any further thoughts on this? 

IMO I think it should be removed since the functionality is contained elsewhere. 

What could potentially be added to it to make it more useful?

**Comment by damianmarti** [comment]
Yes, we can remove useAccountBalance, but maybe we should add how to get the ETH price somewhere in the docs.

**Comment by technophile-04** [comment]
> we can remove useAccountBalance, but maybe we should add how to get the ETH price somewhere in the docs.

Yup agree, maybe we could have a utils section in docs.scaffoldeth.io where we can this and also about some other utils like `getBlockExplorerTxLink`, `notification` etc. Or this might be one of the [recipes](https://docs.scaffoldeth.io/recipes) ! 

But yeah lets remove `useAccountBalance` @Hotmanics you want to tackle this ? Please feel free to ask if you need any help 🙌

**Comment by Hotmanics** [comment]
> > we can remove useAccountBalance, but maybe we should add how to get the ETH price somewhere in the docs.
> 
> Yup agree, maybe we could have a utils section in docs.scaffoldeth.io where we can this and also about some other utils like `getBlockExplorerTxLink`, `notification` etc. Or this might be one of the [recipes](https://docs.scaffoldeth.io/recipes) !
> 
> But yeah lets remove `useAccountBalance` @Hotmanics you want to tackle this ? Please feel free to ask if you need any help 🙌

For sure! Hopefully have something here in the next day or two for it!
