### ISSUE TITLE
bug: lack of "use client" breaks the AddressInput component

### ISSUE THREAD

**Issue by derrekcoleman** [scaffold-eth/scaffold-eth-2#698]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Current Behavior

Clicking an address in the left sidebar on the Debug page throws this error.
<img width="974" alt="Screenshot 2024-01-22 at 3 22 57 PM" src="https://github.com/scaffold-eth/scaffold-eth-2/assets/80121818/cf525e0e-78dd-4caa-b2dc-82f200d67154">

### Expected Behavior

Expect clicking the address to take me to http://localhost:3000/blockexplorer/address/[0x...], the blockexplorer page for that address.

### Steps To Reproduce

Fresh git clone install, start chain and frontend, go to Debug tab, click the owner
<img width="1188" alt="Screenshot 2024-01-22 at 3 26 41 PM" src="https://github.com/scaffold-eth/scaffold-eth-2/assets/80121818/20c0ab6d-0a9a-40bd-b55a-8d07bbe1226c">
 address.

### Anything else?

Clearly a server component issue. Here's the terminal output. 
<img width="1285" alt="Screenshot 2024-01-22 at 3 28 09 PM" src="https://github.com/scaffold-eth/scaffold-eth-2/assets/80121818/0724db09-56f8-4aa6-9a20-516ffdc0bff0">

**Comment by derrekcoleman** [comment]
Adding "use client" to the top of these files got the page to load. Other input components probably need the same.
AddressInput.tsx, EtherInput.tsx, IntegerInput.tsx

Since I'm new to the party, I'd love some guidance. **Would it be useful for me to make a PR that adds "use client" to these Input components?** If so, I'd follow the process outline in CONTRIBUTING.md.

Or maybe I'm missing something! I'm new to the app router, so maybe I've got something fundamentally off on my side that doesn't require a change to SE-2.

**Comment by technophile-04** [comment]
Hey @derrekcoleman tysm for raising the issue ! Yeah actually this is caused because of #688 which we merged few hours ago. Adding "use client" on top of `AddressInput` gives the warning checkout mentioned in #686 

A simple solution is adding "use client" at the top of `packages/nextjs/components/scaffold-eth/Input/index.ts` 

@derrekcoleman could you please create a PR with the above solution, Thanks 🙌

Am gonna create a detailed issue/comment on why this happened later

**Comment by technophile-04** [comment]
Thanks @derrekcoleman !! fixed at #699 closing this

**Comment by derrekcoleman** [comment]
You move quickly 🙌 

Thanks for the clear response and encouragement.
