### ISSUE TITLE
Slow typing on <AddressInput> causes cursor stealing

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#710]
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/2486142/dddf5301-1b39-4418-8e33-f1a52792b379)

If you are writing your ENS on AddressInput (slowly after the dot), it "steals" the cursor... and if you try to keep typing, the cursor is not there :D

Notice this testing ABI Ninja with Austin. But it's also happening here.

Let me know if it's clear. If not I can record a video.

**Comment by JohnCorrigan1** [comment]
Just ran into this. Input is disabled when trying to resolve ENS and does not refocus. I updated my local to disable input on success instead of on loading from the wagmi hook.

I can submit a pr if this is a valid solution.

**Comment by technophile-04** [comment]
Playing around with it, will create a PR soon 🙌


https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/4c51a76d-1db9-4c0c-85a3-49f0990e9118
