### ISSUE TITLE
bug: cannot yarn verify --network arbitrumGoerli

### ISSUE THREAD

**Issue by kmjones1979** [scaffold-eth/scaffold-eth-2#715]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Current Behavior

Results in Error: `getaddrinfo ENOTFOUND api-goerli.arbiscan.io `

The endpoint seems down...
```
$_ curl -i https://api-goerli.arbiscan.io/api
curl: (6) Could not resolve host: api-goerli.arbiscan.io
```

I am guessing Arbitrum is planning to shutdown goerli. Should we just remove it and replace with arbitrumSepolia?

### Expected Behavior

Verification success :)

### Steps To Reproduce

yarn verify --network arbitrumGoerli

**Comment by technophile-04** [comment]
Ohh yes ! 

![Screenshot 2024-02-10 at 3 38 25 PM](https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/ddc51e66-3241-45fc-9f2b-4ed293802c07)


I think they also have removed the whole block explorer for goerli https://docs.arbitrum.io/node-running/node-providers#arbitrum-public-rpc-endpoints
