### ISSUE TITLE
bug: create-eth foundry is failing with a rainbowkit dependency issue?

### ISSUE THREAD

**Issue by austintgriffith** [scaffold-eth/scaffold-eth-2#727]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

npx create-eth@latest

### Steps To Reproduce

npx create-eth@latest

choose foundry 

### Anything else?

![IMAGE 2024-02-14 13:57:34](https://github.com/scaffold-eth/scaffold-eth-2/assets/2653167/3b770e49-769c-4d02-8826-9e9086c58611)

**Comment by technophile-04** [comment]
Should be fixed in latest version https://github.com/scaffold-eth/scaffold-eth-2/pull/729 🙌
