### ISSUE TITLE
Invalid method signature

### ISSUE THREAD

**Issue by pedromnchunks35** [scaffold-eth/scaffold-eth-2#751]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Current Behavior

I have used all the ways the documentation says i should write information into the blockchain.
I am running the blockchain locally.
When i use the hooks to create the transaction it says "unrecognized-selector"
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/48800536/c6b9f013-6a9a-4264-8e5e-0ef215c94eed)
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/48800536/28184b76-7588-42a5-b295-255be66dcd72)

### Expected Behavior

It should create the transaction sucessfully since i entered the same parameteres as i inserted in the unit testing i did over the contract.
The tests work and the abi is actually generated.. i dont really understand what is going on.

### Steps To Reproduce

1. yarn chain
2. yarn deploy
3. yarn start
4. creating a write hook and entering the requested parameters
5. invoke the write hook
The abi is generated correctly like you can see here:
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/48800536/aafe2b5c-5e6e-4c78-8466-89fb2686486a)
In this print i am using the scaffoldcontract hook but i already tried with scaffoldwrite hook and the result is the same:
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/48800536/5af57630-3e1d-4f55-84e2-26c5b00701bc)
In this print you can see that i am inserting the values manually just for testing and it still does not work:
![image](https://github.com/scaffold-eth/scaffold-eth-2/assets/48800536/02701327-a346-4d4e-9d18-fb44c4585427)

**Comment by rin-st** [comment]
it seems this error appears in some cases when you use metamask with hardhat. So, if you're using MetaMask, try to use Burner wallet.

If it's not the case check out this [SO question](https://stackoverflow.com/questions/72101643/hardhat-what-are-the-strange-calls-to-my-smart-contract). Also, probably [this](https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/315#discussioncomment-3937306) can help
