### ISSUE TITLE
Update CLI scaffolded README

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-2#755]
### Description : 

Currently, after scaffolding project through CLI the monorepo  README always shows hardhat instruction due to : 

https://github.com/scaffold-eth/scaffold-eth-2/blob/cli/templates/base/README.md

We can tackle this with two approaches : 

Simple : 
- Update [`templates/base/README.md`](https://github.com/scaffold-eth/scaffold-eth-2/blob/cli/templates/base/README.md) such that it contains both hardhat and foundry instruction checkout https://docs.scaffoldeth.io/quick-start/environment

Better approach: 
- We can create separate README's for both one in [`templates/extensions/hardhat`](https://github.com/scaffold-eth/scaffold-eth-2/tree/cli/templates/extensions/hardhat) for hardhat and second inside [`templates/extensions/foundry`](https://github.com/scaffold-eth/scaffold-eth-2/tree/cli/templates/extensions/foundry) with their respective instruction. 

Second approach make more sense to me since when

**Comment by carletex** [comment]
I like the second one better too!

**Comment by technophile-04** [comment]
Completed in #782
