### ISSUE TITLE
Example UI page

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#81]
On SE-1 we have a example-ui page where it shows the possibilities you have when using scaffold (sending tx, reading contract data, showing logged events, showing antd capabilities, etc). It focus more on the functionality that in the UI itself (it has the same style as the rest of the pages).

For SE-2, my idea is:

=> Having a completely **different UI** for this page (main SE-2 UI is simple & minimal). Let's have a fancy landing page for /example-ui. (We will use different colors, layouts, etc)

=>  **Functionality**. This is where I'd love to hear what people think about what to add / not to add. This will be related with the default solidity contract that we have (check #80).

Some random ideas:
- Send tx ("mint a purpose" from the contract)
- Show Balance of the contract
- Show event log
- Withdraw from the contract
- Some text / link to tailwind, daisy, react use.

Thoughts?

**Comment by rin-st** [comment]
I believe functionality should be as simple as possible - just to show how it works. So probably, your ideas are enough.

Having a completely different UI is an awesome idea! What about adding scripts and instructions how to deploy the app, for example, to surge like in sre? After deploying the app header page buttons should be removed and the logo/logo text changed so the user will have a completely ready frontend for his app. Smth like this but styled better 😄 
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/25638585/213283380-ea27ae90-64a3-44f5-89a3-32846cfff8b3.png">

**Comment by carletex** [comment]
Closing this. We'll be creating individual issues like this: https://github.com/scaffold-eth/scaffold-eth-2/issues/466
