### ISSUE TITLE
When you disconnect your burner wallet (with MM closed) it does not show Connect button

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/scaffold-eth-2#843]
Instead it shows a fake "Wrong network" button, like if you were connected to your MetaMask wallet, but MM is closed, so Switch network does not work, and Disconnect button does not work on the first click.

Only happens first time you access (with MetaMask closed). Then after you correctly disconnect, and connect again with burner, it works fine.

Steps to reproduce:
- Fresh SE-2 repo with hardhat connection configured
- Make sure Metamask is not logged in
- `yarn install` + `yarn chain` + `yarn deploy` + `yarn start`
- Your burner wallet should be autoconnected
- Click "Disconnect"

<details><summary>Check video</summary>

![burner-wallet-disconnect-MM-closed](https://github.com/scaffold-eth/scaffold-eth-2/assets/55535804/528c640e-8f74-4cb2-a601-e41b08f6606f)
</details>

**Comment by technophile-04** [comment]
What do you mean by MM closed or not logged in ? Does it mean : 
- Disconnecting from website through MM interface or 
- Locking the metamask ? 

I tried both, but was not able to reproduce :(, I think I am missing though, here is what I did : 


<details>

<summary>
Locking metamask : 
</summary>

https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/fbc7087f-314b-4dd5-af90-264eb998a0da

</details>

<details>

<summary>
Disconnecting from website : 
</summary>

https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/778217d7-e060-43f7-b961-4387c4a9f7a2

</details>

For me, when switching from burner wallet to metamask the middle phase is always : Click connect button + select metamask from modal 

But yeah I might have missed something would love to know, Thanks @Pabl0cks 🙌

**Comment by Pabl0cks** [comment]
> I tried both, but was not able to reproduce :(, I think I am missing though

Sorry Shiv! I should have recorded full screen, I meant with Metamask locked. It happened to me first while testing a Challenge, so went to SE-2 to check if the problem was also there. 
**Anyways, I just tried with computer just switched on, and works well in both Desktop and Laptop.**

I've been having cache problems while testing in hardhat since last Metamask update, probably it was a cache issue too 😥

> For me, when switching from burner wallet to metamask the middle phase is always : Click connect button + select metamask from modal

Since a few days ago (or last Metamask update probably), if I had Metamask logged in (not locked), when I disconnect from the burner wallet, it would autoconnect to my Metamask wallet. I think that's probably the origin of my problem, but don't know at what point the behavior starts, at some point after testing for a while in hardhat. Will try to monitor, and see if it happens in my laptop also.

I think we can close, I always can reopen if I find a consistent way to reproduce 🙌 

Sorry for making you lose time on this @technophile-04 !! ♥

**Comment by rin-st** [comment]
I've seen something like that in the last few days. I'll let you know if I find a way to 100% reproduce it
