### ISSUE TITLE
Discussion: Connect button when Burner wallet is connected.

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth-2#87]
**This is an open discussion, we might create a few issues from this**

The burner wallet looks like this on app init.

![image](https://user-images.githubusercontent.com/2486142/210970967-bc3bceb8-aa06-4c03-a794-6eedbfdb37be.png)

If you want to connect your wallet (metamask, etc), you have to click the address, disconnect, click connect & select your wallet.

![image](https://user-images.githubusercontent.com/2486142/210971698-6375beff-5ddd-4ccb-8a2b-7d70bfe4ce0f.png)

Should we have a directo connect button (that disconnects the burner wallet, and open the modal to select the new wallet to connect?)

A couple of more things to comment on:
- I think we should show indicate in a better way that the wallet you get when you start the app is a burner wallet (maybe an icon /  using opacity / show a ℹ️ with more info /..), because it might be a little confusing for newcomers to SE seeing that random wallet connected.
- Network Switch: I think we need to show the network we are connected to, but not necessarily the network switch. In SE-1 there is a flag to show / hide. Here we could have a prop for the `RainbowKitCustomConnectButton`. 
  - And maybe hide it completely when the burner wallet is connected? Since we only want to use burner wallets in a localchain:
  
![image](https://user-images.githubusercontent.com/2486142/210973111-e953f280-1b1e-4aa3-88a9-98e6dc9b1a0e.png)

**Comment by technophile-04** [comment]
> Should we have a directo connect button (that disconnects the burner wallet, and open the modal to select the new wallet to connect?)

💯 we need this!

> I think we should show indicate in a better way that the wallet you get when you start the app is a burner wallet (maybe an icon / using opacity / show a ℹ️ with more info /..), because it might be a little confusing for newcomers to SE seeing that random wallet connected.

💯
maybe something like this ? 
![Screenshot 2023-01-09 at 11 20 07 AM](https://user-images.githubusercontent.com/80153681/211247665-8016fd0b-20a1-47d4-afee-f825d6af5782.jpg)
and for the info about the burner wallet maybe we can add it to the modal(also the avatar should denote its burner) : 
![Screenshot 2023-01-09 at 11 23 17 AM](https://user-images.githubusercontent.com/80153681/211248103-f6f12c5d-8d54-4dd8-9c31-d20c1e35b4b4.jpg)
don't know if that's possible. 

> Network Switch: I think we need to show the network we are connected to, but not necessarily the network switch. In SE-1 there is a flag to show / hide. Here we could have a prop for the RainbowKitCustomConnectButton.
And maybe hide it completely when the burner wallet is connected? Since we only want to use burner wallets in a localchain:

💯

**Comment by carletex** [comment]
Love this @technophile-04 

![Screenshot 2023-01-09 at 11 20 07 AM](https://user-images.githubusercontent.com/80153681/211247665-8016fd0b-20a1-47d4-afee-f825d6af5782.jpg)

I can see hovering the 🔥and getting some tooltip saying something about BW. 

> and for the info about the burner wallet maybe we can add it to the modal(also the avatar should denote its burner) :

That would be cool also. We can check if Rainbowkit allow us to customize it in a easy way.

From https://www.rainbowkit.com/docs/:
![image](https://user-images.githubusercontent.com/2486142/211287526-a8ceddf1-324d-4dea-ad35-56f35f5627cd.png)

I'll be creating some SE-2 GH issues with some of this stuff.

**Comment by KcPele** [comment]
> **This is an open discussion, we might create a few issues from this**
> 
> The burner wallet looks like this on app init.
> 
> ![image](https://user-images.githubusercontent.com/2486142/210970967-bc3bceb8-aa06-4c03-a794-6eedbfdb37be.png)
> 
> If you want to connect your wallet (metamask, etc), you have to click the address, disconnect, click connect & select your wallet.
> 
> ![image](https://user-images.githubusercontent.com/2486142/210971698-6375beff-5ddd-4ccb-8a2b-7d70bfe4ce0f.png)
> 
> Should we have a directo connect button (that disconnects the burner wallet, and open the modal to select the new wallet to connect?)
> 
> A couple of more things to comment on:
> 
> * I think we should show indicate in a better way that the wallet you get when you start the app is a burner wallet (maybe an icon /  using opacity / show a information_source with more info /..), because it might be a little confusing for newcomers to SE seeing that random wallet connected.
> * Network Switch: I think we need to show the network we are connected to, but not necessarily the network switch. In SE-1 there is a flag to show / hide. Here we could have a prop for the `RainbowKitCustomConnectButton`.
>   
>   * And maybe hide it completely when the burner wallet is connected? Since we only want to use burner wallets in a localchain:
> 
> ![image](https://user-images.githubusercontent.com/2486142/210973111-e953f280-1b1e-4aa3-88a9-98e6dc9b1a0e.png)

There should jus

**Comment by KcPele** [comment]
For the disconnect button. It should show the connect button when someone disconnects from the burner wallet. 
A better way to display a burner wallet is to have an ens name for a burner wallet. it should be something like burnerwallet.eth and it should have an icon beside it
