### ISSUE TITLE
bug: Type error: Type 'string' is not assignable to type '`0x${string}`'.

### ISSUE THREAD

**Issue by dimitrihartt** [scaffold-eth/scaffold-eth-2#870]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Current Behavior

Failed to compile.
./app/blockexplorer/_components/AddressComponent.tsx:22:26
Type error: Type 'string' is not assignable to type '`0x${string}`'.
> 22 |                 <Address address={address} format="long" />
     |                          ^
Error: Command "yarn run build" exited with 1

### Expected Behavior

That String could be assignable to Address

### Steps To Reproduce

Deploying to vercel using git clone.

**Comment by technophile-04** [comment]
Hey thanks @dimitrihartt for creating the issue! Checking it out now 

but unit then you can by pass the error on vercel by running : `yarn vercel:yolo --prod`
