### ISSUE TITLE
bug: Not Able to use frames.js in their Next.js Project 

### ISSUE THREAD

**Issue by anuragasawa20** [scaffold-eth/scaffold-eth-2#877]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Current Behavior

In changing the layout.tsx file of next I tried to implement the code of frames.js to creating frame giving me error 
<img width="1121" alt="image" src="https://github.com/scaffold-eth/scaffold-eth-2/assets/99682976/113d0eaf-bffd-4333-8303-d2736c8820e9">

### Expected Behavior

This should be load the layout of frames.jsx as this actually happening in normal next.js enviornment.

**Comment by anuragasawa20** [comment]
in layout.tsx when I'm using fetchMetadata import it's giving the error. else it's running. 
<img width="1040" alt="image" src="https://github.com/scaffold-eth/scaffold-eth-2/assets/99682976/2da2b1df-0b98-4bb2-906b-262fe461a481">

**Comment by technophile-04** [comment]
Hey @anuragasawa20, could you please provide a minimal reproducible repo link? With cloning the SE-2 and adding frame.js with minmal changes to it?

**Comment by technophile-04** [comment]
Closing this for now
