### ISSUE TITLE
useScaffoldEventHistory uses data from old fetch with different filters

### ISSUE THREAD

**Issue by phaitonican** [scaffold-eth/scaffold-eth-2#903]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Which method was used to setup Scaffold-ETH 2 ?

git clone

### Current Behavior

I use useScaffoldEventHistory twice on a single page with different filters. It fetches right data. I run again and the old data does not change, it use overrides the data with first run of useScaffoldEventHistory (even the constants have a differnt name). Any ideas??

This:

```
<PostCardList key="-1" filters={{ _post_hash: postHash }} />
<PostCardList key="-2" filters={{ _parent_post_hash: postHash }} />
```
and PostCardList.tsx:

```
export const PostCardList = ({ filters }: PostCardListProps) => {

const { data: postCreatedEvents, isLoading } = useScaffoldEventHistory({
    contractName: "PostCreator",
    eventName: "PostCreated",
    fromBlock: 0n,
    watch: true,
    filters: filters 
  });
...
```

But the second One gets overridden with contents of first one?? Both solidity parameters are indexed. And I also put a key inside my looped list items (unique hash)

### Steps To Reproduce

Use useScaffoldEventHistory on same page with different filters

**Comment by technophile-04** [comment]
Thanks @phaitonican! Would appreciate if you could share an link to minimal reproducible repo with example simple contract and using the hook on same page causing problem.

**Comment by phaitonican** [comment]
Hello. Here is the minimal reproduciable repo https://github.com/phaitonican/scuffold-eth-2-event-history-test

Just have open `http://localhost:3000/test` site. It call component with useScaffoldEventHistory twice, but the retrieved data gets overriden (by one which loads slower)

**Comment by rin-st** [comment]
@phaitonican please add changes from suggested pr and check if it works for you

**Comment by phaitonican** [comment]
It does work thanks very much
