### ISSUE TITLE
Scaffold-ETH #2 Documentation: Code Comments 

### ISSUE THREAD

**Issue by edakturk14** [scaffold-eth/scaffold-eth-2#91]
Create the docs for the best developer experience, starting with code comments for the followings:

**Hardhat**

- [x] YourContract.sol
- [x] 00_deploy_your_contract.ts
- [x] hardhat.config.ts
- [x] .env.example

**NextJS**
- [ ] example-ui.tsx (still in progress https://github.com/scaffold-eth/se-2/issues/81)
- [ ] tailwind.config.js
- [ ] _app.tsx
- [ ] .env.development

**Comment by carletex** [comment]
Hey @edakturk14 

As we discussed, listing here the files that would be nice to add comments to (some of them might be commented already: we can review & tweak).

**Hardhat**
- YourContract.sol
- 00_deploy_your_contract.ts
- hardhat.config.ts
- .env.example

**NextJS**
- example-ui.tsx (this might be the one we need to comment the most... but still in progress #81)
- tailwind.config.js
- _app.tsx
- .env.development

Happy to add some ideas for comments on any of these files.

**Comment by edakturk14** [comment]
thanks @carletex! these are super suggestions, I've updated the issue to reflect all the files we should be covering. Hope thats okay! I'll continue to work on these files

**Comment by Chirag018** [comment]
Hey, @edakturk14 would like to work on example-ui.tsx and _app.tsx file to add documentation for the same.

**Comment by edakturk14** [comment]
hey @Chirag018 sure, feel free to make a PR for it!

**Comment by sverps** [comment]
@Chirag018 It could also be useful to read the following bit on comments first: "[typescript styleguide: comments-documentation](https://google.github.io/styleguide/tsguide.html#comments-documentation)"

We're trying to follow this style guide a bit. It's not set in stone, but it serves as a solid starting point, see also discussion in #232

**Comment by syed-ghufran-hassan** [comment]
Can I participate in this section?

Hardhat

YourContract.sol
00_deploy_your_contract.ts
hardhat.config.ts
.env.example

Particulartly for this please

**Comment by technophile-04** [comment]
Hey thanks @syed-ghufran-hassan, actually we had already updated those files at #96 and #106

Closing this, thanks all 🙌
