### ISSUE TITLE
Forge flags not being passed on latest foundry branch

### ISSUE THREAD

**Issue by escottalexander** [scaffold-eth/scaffold-eth-2#948]
@technophile-04 
On the latest foundry branch this new issue exists due to the use of Make.
Prior to the introduction of the Makefile you could run
```bash
yarn foundry:test -vvvv
```
 or `--match-test`, etc. and get trace logs on the tests. 

Now the extra flags are processed by Make and so you get this output: 
```bash
[elliott@fedora token-voting]$ yarn foundry:test -vvv
GNU Make 4.4.1
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[elliott@fedora token-voting]$ 
```

**Comment by technophile-04** [comment]
Ohhh you are right! we need to find a way to make sure that flags passed through or another solution might be just have `-vvvv` by default? Will try to tinker on this Thanks @escottalexander !

**Comment by escottalexander** [comment]
While you are considering this it would also be pretty crucial IMO to have the `--match-test "TEST_NAME"` flag as well. If you have several failing tests and are using the -vvvv flag then the output is overwhelming. Always helps to narrow it down to a single test.

**Comment by technophile-04** [comment]
Hey @escottalexander created #950, I think other than test it not much needed to pass in flags? If there are some edge cases people can always `cd packages/foundry` and run commands for their choices?

**Comment by escottalexander** [comment]
@technophile-04 Yes! This seems to be a good way around the problem. I agree that there aren't any other commands that require passing arguments that I use commonly. Tested your solution and it works well for me.
